### ISSUE TITLE
Validating dynamically added nested form fields

### ISSUE THREAD

**Issue by nathanvda** [DavyJonesLocker/client_side_validations#318]
Hi there, I am the maintainer of the cocoon gem, which allows to dynamically build nested forms by removing and adding partials.

Now I had an issue posted that it was impossible to use together with client-side-validations. So I tried to make it work, and what I tought should fix it was call `$('form[data-validate]').validate()`, but that does not work for me.

I have a test-project that reproduces the error: https://github.com/nathanvda/formtastic-cocoon-client-side-validations-demo

Could you have a look at what I am doing wrong?

Thanks in advance!

**Comment by joshforeman** [comment]
@nathanvda - I saw your example repo using formtastic. Have you revisited this since?

I have it working using the error messages approach, but can't get it working inline for the nested form.
