### ISSUE TITLE
jQuery Mobile Support

### ISSUE THREAD

**Issue by bcardarella** [DavyJonesLocker/client_side_validations#36]
There seem to be several issues before this will work.
1. Because the pages are loaded via AJAX the forms can be inserted into the DOM without the .validate() function running. (currently runs after page load) I'll probably have to use the 'ajaxComplete' event.
2. Even when forcing the form to setup after it is inserted in the DOM the form seems to be running validation right away.

**Comment by tagliala** [comment]
Closing here
