### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validators' of undefined

### ISSUE THREAD

**Issue by mledom** [DavyJonesLocker/client_side_validations#387]
I'm getting the Uncaught TypeError: Cannot read property 'validators' of undefined when trying to validate a field.
I've trying to figure out where window.ClientSideValidations.forms is being populated with anything other than the initialization window.ClientSideValidations = {
    forms: {}
I'm using:
- rails (3.2.7)
- simple_form (2.0.2)
- client_side_validations (3.2.0.beta.6)
- client_side_validations-simple_form (2.0.0.beta.2)

**Comment by AndriySand** [comment]
I had the same error and then I found error there, I used
<%= form_for @zipcode, html: { class: "form-horizontal", validate: true } do |f| %>
when I replaced it with this code everything started work fine
<%= form_for @zipcode, html: { class: "form-horizontal" }, validate: true do |f| %>
Best wishes
