### ISSUE TITLE
resetClientSideValidations for a specific field only?

### ISSUE THREAD

**Issue by stevenringo** [DavyJonesLocker/client_side_validations#424]
Hi,

We have a form that has an "optional" section. For example a checked checkbox might indicate that additional information must be filled in.

I can toggle the validations in the optional section using enableClientSideValidations() and disableClientSideValidations() respectively, however if the checkbox is later unchecked I would like to clear the messages etc already shown. I tried using resetClientSideValidations(), but this seems to work only on the entire form, not at a field level.

Any idea on how to do this, short of adjusting the error message css manually?

Thanks!

Steve

**Comment by weavermedia** [comment]
For anyone copy/pasting @bcardarella's lines above - there's a typo.

Should read:

```javascript
$(input).disableClientSideValidations();
$(form)[0].ClientSideValidations.removeError($(input));
```

**Comment by tagliala** [comment]
@weavermedia thanks, comment updated fwiw :+1:
