### ISSUE TITLE
custom validation suggestion for README

### ISSUE THREAD

**Issue by ccmcbeck** [DavyJonesLocker/client_side_validations#445]
When I was evaluating this gem, I wondered if I could use it for all my client_side validations.  I've seen threads on Railscasts, the simple_form Google Group, etc where people wonder the same thing.  

We all want the goodness of c_s_v, but nothing is worse than having multiple validation engines dueling away in the UI (so I'm glad to see you are working on a backbone.js plugin).

To allay these fears, it would be nice if the README documented a few more custom validation use cases.  Forex, I wanted to see a pattern for validations that depend on multiple attributes to fire when either field changes.  I extracted my solution from: https://github.com/bcardarella/client_side_validations/wiki/Shared-validations-for-multiple-fields

```
$('#last_name, #company')
      .change(-> $('#first_name').change(); true)
      .focusout(-> $('#first_name').focusout(); true)
```

My validation decorates `#first_name` with the error, but now it fires when the other fields are modified or visited.  This may seem obvious to some, but it took me a while to figure it out.  I think if more people knew up-front (on the README) how comprehensive this gem was for all your validation needs, they would dive in faster.  I wish I had done it sooner.

Just my 2 cents.

**Comment by tagliala** [comment]
Don't know if this is still an issue

There is a wiki for custom validators at https://github.com/DavyJonesLocker/client_side_validations/wiki/Custom-Validators
