### ISSUE TITLE
TypeError: Cannot read property 'validators' of undefined

### ISSUE THREAD

**Issue by bolshakov** [DavyJonesLocker/client_side_validations#450]
client_side_validations (3.2.1)
client_side_validations-formtastic (2.2.1)

I'm getting this error while trying to submit the form:

> TypeError: Cannot read property 'validators' of undefined

It happens here: 

``` JavaScript
_ref = {
  'submit.ClientSideValidations': function(eventData) {
     if (!$form.isValid(form.ClientSideValidations.settings.validators)) { // <-- this one
       eventData.preventDefault();
       return eventData.stopImmediatePropagation();
```

**Comment by ianakiara** [comment]
+1

**Comment by Rubab-Syed** [comment]
I'm experiencing the same issue. form.ClientSideValidations.settings is undefined. Any help?

**Comment by tagliala** [comment]
@Rubab-Syed please open a new issue providing all the information required.

Ref: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue
