### ISSUE TITLE
Have to click submit button twice to submit form.

### ISSUE THREAD

**Issue by marnold1** [DavyJonesLocker/client_side_validations#469]
Occurs under this scenario.

1) Submit a form with validation errors.
2) Correct all the errors but dont tab out of the last item fixed. So the error message remains.
3) Click down on the submit button (validation occurs on mousedown removing error messages so form and button shifts upwards). On mouseup the submit button has moved so no longer triggers the submission.
4)Now there are no error messages the submit button can be selected again to submit the form.

Is it possible to change the triggering events so it validates on mouseup? I see this error on the contact form for http://zinergia.co/.

Note: I know this would work if all error messages were inline but that does not work for our design.

**Comment by anthony-robin** [comment]
any news on this?

**Comment by tagliala** [comment]
Hi,

I'm switching down old issues.

I hope this is not an issue anymore, otherwise feel free to start a new one providing an up-to-date reduced test case

**Comment by anthony-robin** [comment]
Yes, this is still an issue. I will start a new one.
