### ISSUE TITLE
Move back to JavaScript

### ISSUE THREAD

**Issue by bcardarella** [DavyJonesLocker/client_side_validations#492]
Coffeescript, while I like the syntax, is not future-proof. See: http://meta.discourse.org/t/is-it-better-for-discourse-to-use-javascript-or-coffeescript/3153/11

It also adds extra complexity to the build and release process that has caused issues. Some contributors have updated the coffeescript without generating the JavaScript. Let's just remove this extra step.

We can start with the generated JavaScript from the existing build.

**Comment by tagliala** [comment]
I would like to move to es6 + webpack base builder
