### ISSUE TITLE
4.0 upgrade path

### ISSUE THREAD

**Issue by bcardarella** [DavyJonesLocker/client_side_validations#494]
Here is how I want to handle updating CSV for Rails 4.0:

* 4.0 will be a major version change for CSV so we will get to change a lot of stuff as we will not have backwards compatibility with 3.x

* I would like to eventually move over to the `master` branch and that will always build for Rails 4.0 and should pass the test suite.

* I don't see CSV 4.0 coming out for at least 2 months after Rails 4.0 lands (hopefully not that long) as there will be major changes on the JavaScript side of things. Because it will take so longer and people will want a Rails 4.0 compliant version of CSV suggesting they use master branch or perhaps releasing a `alpha` or `pre` version to partially satisfy them while we update might be the correct option.

* I want to write an override for `ActiveModel::Validations::Confirmation`. This Validator is a constant pain for CSV. I got part of that pain out of the way with this commit back to Rails: https://github.com/rails/rails/commit/fcc534ed76a7ef50bf7887378ce6c68d5ace336c but it does not go far enough. I will create a new issue for this eventually to describe in more detail. We will have to document in the gem that we are overriding the default confirmation validator.

* The JavaScript test suite will be extracted into another gem called `client_side_validations-dev` so that it can be added easily to the other plugins. This is much easier than updating all over the place.

* The gem will be moved to the @DockYard organization

**Comment by dmur** [comment]
Any updates?  Is this project deprecated?

**Comment by tagliala** [comment]
@msokk please use the current master branch

closing here
