### ISSUE TITLE
build_validation_options fails if child_index is not a string

### ISSUE THREAD

**Issue by jprosevear** [DavyJonesLocker/client_side_validations#500]
build_validation_options fails if child_index is not a string.  Regexp.escape will fail.

child_index is passed as a fixnum sometimes, as per:
http://railscasts.com/episodes/196-nested-model-form-revised

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
