### ISSUE TITLE
Validating size of file

### ISSUE THREAD

**Issue by travisvalentine** [DavyJonesLocker/client_side_validations#502]
I see in the [wiki](https://github.com/bcardarella/client_side_validations/wiki/Paperclip) that there is a way to `validate_presence_of` a file uploaded with Paperclip, but was wondering if there was a way to validate the file's size.

**Comment by eliotsykes** [comment]
Just highlighting this for developers searching for Paperclip and client side validations for attachment file size and Content-Type, check out the wiki page section: https://github.com/DavyJonesLocker/client_side_validations/wiki/Paperclip#size-and-content-validation

**Comment by tagliala** [comment]
@eliotsykes thanks

Since CSV is supposed to support IE >= 8, could you please clarify browser compatibility and an alternative way to load it without turbolinks?

**Comment by eliotsykes** [comment]
Hi @tagliala - thanks that section has been there a long time, not written by me. I added notes today that's all. I'll add what I can from what you suggested.

**Comment by tagliala** [comment]
Thanks.

> `size: { in: 0..10.megabytes }`

Does this work? I'm seeing that javascript only checks for `less_than_or_equal_to`

**Comment by eliotsykes** [comment]
@tagliala - that wouldn't work as is, nor would `less_than` or the other possible options, it'd need modifying. I've adjusted the original code snippets to similar to what I'm using locally. Its now using `less_than`, and this would not work with other options, it would need further modification.
