### ISSUE TITLE
Conditional validation doesn't work on collection select

### ISSUE THREAD

**Issue by coorasse** [DavyJonesLocker/client_side_validations#506]
If you use a select tag for a field wich presence is conditional validated, the client side validation doesn't work:
`<%= f.collection_select(:quorum_id, @group.quorums.active.all, :id, :name, :prompt => t('pages.proposals.new.quorum_prompt'), :validate => true ) %>`

and in the model
`validates :quorum_id, :presence => true, :if => :is_standard?`

the field is not validated.

If I use a text_field it is correctly validated

**Comment by azam-noob** [comment]
Any progress on this problem so that we can use `validates :title, presence: true, length: { minimum: 6, maximum: 32}, if: :on_first_step?` instead of `validates :topics, presence: {if: :on_first_step?}`?
