### ISSUE TITLE
focusout not firing after validation

### ISSUE THREAD

**Issue by wakiki** [DavyJonesLocker/client_side_validations#514]
Since client_side_validations 3.2.5, focusout doesn't seem to firing if validation fails. 

focusout is still fired if validation passes. 

Anyone any ideas?

I'm also using client_side_validations-formtastic 2.2.1.

Steve

**Comment by jmarceli** [comment]
I'm also having problems with `focusout`. My working solution is:

    window.ClientSideValidations.callbacks.element.after = function($element, message, callback) {
      // here your focusout code
      // $element is the element which triggers focusout event
    }
   
For me it seems that `focusout` event is somehow intercepted by clientside validations gem.

**Comment by tagliala** [comment]
@jmarceli I would need a failing test case

Could you please open a new issue? You should also specify which version of the gem you are using

**Comment by jmarceli** [comment]
Sorry for the mess. I was just inspecting the old code and found this workaround, but `focusout` seems to be working as well (at least in my case).

**Comment by tagliala** [comment]
@jmarceli don't worry

Can I close this issue?

**Comment by jmarceli** [comment]
For me it's OK.

**Comment by tagliala** [comment]
thanks. closing here
