### ISSUE TITLE
Built-in Android browser select input validation issues

### ISSUE THREAD

**Issue by ghost** [DavyJonesLocker/client_side_validations#521]
I'm only experiencing this issue in the android built-in web browser. On any of my select input fields that are validated, I'm having an issue where the user picks an option from the select input and instead of the select box showing the option, it shows it empty with the validation running and seeing it blank. The user has to go back to the select box a second time and pick an option for it to actually "select" an option and show it.

I've not ran into this problem with any other browser so far, and if I disable validations for the form, the select boxes operate normally. Has any body ran into this issue in the android browser with their select box validations or have an idea what might be happening? 

Update: forgot to mention, the validation is actually being fired when the select box is pressed and the options come up before an option is even picked.

![error](https://f.cloud.github.com/assets/450195/344946/7f9b30c2-9e10-11e2-9cf2-f74166d15713.jpg)

**Comment by betesh** [comment]
Does anyone have a workaround for this?

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

Please note that I only have one android 7.1.1 phone running last Chrome
