### ISSUE TITLE
Problem with fields_for

### ISSUE THREAD

**Issue by onordgren** [DavyJonesLocker/client_side_validations#528]
Hello,

I have a problem when trying to validate a form that is based on dynamically created inputs that is rendered using fields_for. The form code looks like this with an @order that has_many answers.

```
= simple_form_for [@service, @order], validate: true do |f|
  = f.simple_fields_for :answers do |answer_form|
    = answer_form.input :value, validate: answer_form.object.required
```

This works well for most of the time. The problem is however that my answers all have different validations depending if they are required or not. Let say that i render two different selects where the first one i optional and the second is required. The form would look something like

```
<select class="select optional" id="order_answers_attributes_0_selected_value" name="order[answers_attributes][0][selected_value]">
  <option value="">Select</option>
  <option value="1">Option 1</option>
  <option value="2">Option 2</option>
</select>

<select class="select optional" id="order_answers_attributes_1_selected_value" name="order[answers_attributes][1][selected_value]">
  <option value="">Select</option>
  <option value="1">Option 1</option>
  <option value="2">Option 2</option>
</select>
```

However when submitting the form both of the selects would be marked as false. I figured out that the problem is that the script hash contains the following code

```
"order[answers_attributes][][selected_value]":{"presence":[{"message":"required"}]}
```

So that all inputs with [selected_value] at the end will be validated.

Is it possible to override this behaviour and include the index in the script?

Thanks

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

Please note that the proper repo to report simple_form issues is --> https://github.com/DavyJonesLocker/client_side_validations-simple_form
