### ISSUE TITLE
'Password' confirmation message

### ISSUE THREAD

**Issue by amrnt** [DavyJonesLocker/client_side_validations#53]
I don't think the confirm password message is so useful. It should appear on the confirm field, not on the password field.

**Comment by tkbky** [comment]
Is this issue resolved yet? In my rails 4.2.3 app, the confirm password message still appear on the password field instead of the password confirmation field. FYI, I'm using the master branch of this gem.

**Comment by tagliala** [comment]
If there is someone still interested in this issue, let's continue on #630.

Please note that I don't have a fix and I'm looking for help

:lock:
