### ISSUE TITLE
Make it "cache-able" and unobtrusive

### ISSUE THREAD

**Issue by john-999** [DavyJonesLocker/client_side_validations#530]
Hi Brian,

I'm using your gem "client_side_validations" and have just found out that validations won't work anymore once we start caching our apps (which everyone should do) and don't render our JS inline (which nobody should do and also wouldn't follow the "unobtrusive JS" logic). In other words:

As you put in the README: "A rendered form with validations will always have a `<script>` appeneded directly after". Now if you're caching things, the forms get cached as well and won't "yield" the script tags anymore when we put all our JS at the bottom of the page, as we should.

I'm too much of a noob to code this myself, but my suggestion would be:

Create a rake task like...

```
rake client_side_validations:generate_validations_form_objects
```

... which would do the following:
- run through all files in the tree in `app/views/` and check each file for any requested client-side validations
- based on that, generate the content of the required `<script>` tags
- create a new file in `assets/javascripts/`, let's call it `"rails.validations_form_objects"`
- save the generated JS into that file (this would of course then require a manual `"//= require ..."` entry in the file `assets/javascripts/application.js`.

New benefits:
1. All your client_side_validations related JS can now be processed by the asset pipeline
2. Apps can now be cached and still respect "unobtrusive JS"

What do you think?

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

I do agree, but this require very high skills and a lot on effort on my side.

Ref: (#666) (#226) (#490)
