### ISSUE TITLE
Humanize error message

### ISSUE THREAD

**Issue by holgersindbaek** [DavyJonesLocker/client_side_validations#533]
I'm having trouble "humanizing" my error message.

I basically want to do this in my initializer:

```
%{<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first.humanize}.</label></div>}.html_safe
```

That gives an error, so I went on and did this:

```
%{<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first.try(:humanize)}.</label></div>}.html_safe
```

No error there, but it still doesn't work.

How can I get the error string humanized?

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

Never had issues in humanizing CSV errors. It works fine with multiple languages.

I'm using the standard rails i18n feature.
