### ISSUE TITLE
wrong number of arguments (3 for 2) with Rails 4.0.0.RC1, client_side_validations 3.2.5 and simple_form 3.0.0.beta1

### ISSUE THREAD

**Issue by BjoernKW** [DavyJonesLocker/client_side_validations#535]
The following simple form:

<%= simple_form_for(@service) do |f| %>
<%= f.input :name %>
<% end %>

results in the following error:

wrong number of arguments (3 for 2) in app/views/public/index.html.erb, line 8 with line 8 in that file being

<%= simple_form_for(@service) do |f| %>

Root cause is:

(gem) actionpack-4.0.0.rc1/lib/action_view/helpers/form_helper.rb, line 426
(gem) client_side_validations-3.2.5/lib/client_side_validations/action_view/form_helper.rb, line 25

**Comment by ashes999** [comment]
I ran into this problem today. Is this going to be merged back into the main branch and published on RubyGems?

**Comment by tagliala** [comment]
@ashes999 please do not mention @bcardarella I'm the maintainer now.

Please open a new request following our contributing guidelines: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue

I can't confirm this bug: https://travis-ci.org/DavyJonesLocker/client_side_validations-simple_form

**Comment by tagliala** [comment]
also, if this issue is related to the simple form plugin, use this repository: https://github.com/DavyJonesLocker/client_side_validations-simple_form

**Comment by ashes999** [comment]
@tagliala okay, thanks. I have confirmed this bug. I will re-open it on the new repository. FYI, this issue still shows up quite high in Google, which is why I commented here.

**Comment by lessless** [comment]
I assume this is still an issue?

**Comment by tagliala** [comment]
#603 

locking here :lock:
