### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by lemonchis** [DavyJonesLocker/client_side_validations#537]
Hello, 
Im validating a form with client side validations and I also have devise, 
this is in my form, 

 <fieldset>
      <legend>Password</legend>
      <div class="control-group">
        <%= f.label :current_password, "Old password:", :class => "control-label" %>
        <div class="controls">
          <%= f.password_field :current_password %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :password, "New password:", :class => "control-label" %>
        <div class="controls">
          <%= f.password_field :password  %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :password_confirmation, "New password, again:", :class => "control-label" %>
        <div class="controls">
          <%= f.password_field :password_confirmation  %> 
        </div>
      </div>
    </fieldset>

and I have this in my model 
  validates_presence_of     :password, :message => 'required'
  validates_presence_of     :password_confirmation, :message => 'required'
  validates_presence_of     :current_password, :message => 'required'

In the end my view  shows something like this 
![screen shot 2013-05-07 at 6 09 29 pm](https://f.cloud.github.com/assets/2113079/474238/dce3e722-b762-11e2-83c4-26d0225b1dbd.png)

Why are the messages different?
I would like to have all my messages to be consistent. 
How do I change the default message?

Thank you.

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

Please translate "can't be blank" message with "required"

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
