### ISSUE TITLE
validate uniqueness with scope on integer

### ISSUE THREAD

**Issue by rweng** [DavyJonesLocker/client_side_validations#539]
Hi,

I have a `validates :name, uniqueness: {scope: :original_id}`. If in my form the original_id is not set and the name is changed, the following is transfered to the middleware:

```
//validators/uniqueness?case_sensitive=true&scope%5Boriginal_id%5D=&company%5Bname%5D=bl&_=1368602885857
Request Headersview source
```

Now `original_id` is "" in the middleware's params hash. On this, [type_cast_value](https://github.com/bcardarella/client_side_validations/blob/3-2-stable/lib/client_side_validations/active_record/middleware.rb#L33) is called, which convert's the "" to a 0, at least when the column is a `ActiveRecord::ConnectionAdapters::PostgreSQLColumn`.

Now the validation returns true since I have no model with a `name` of "bl" and a `original_id` of 0, however, I do have a company of name 'bl' and original_id null.

I think, "" should be transformed to `null` instead of 0.

In addition to that,Why do the validations in the middleware manually and not use a new klazz instance's `.errors` message? This would have translated the "" correctly to nil.

Thanks :)

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
