### ISSUE TITLE
Uniqueness Validator on edit?

### ISSUE THREAD

**Issue by FelipeKoblinger** [DavyJonesLocker/client_side_validations#542]
Hello! Great geam :+1: 
Well, uniqueness validator is working right on creating a new Customer (example), but when I try to edit this customer the field (email) that contains uniqueness shows "e-mail has been taken". But this Customer have this e-mail. Is possible to work like .valid? method?

Thanks =)

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
