### ISSUE TITLE
Scroll page to first error field

### ISSUE THREAD

**Issue by mcmegavolt** [DavyJonesLocker/client_side_validations#543]
Hello, there!
I have a long form page, when i click Submit button I can't see error fields because they are out of my screen.
How to scroll to first top error filed after form submitting?

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

Yes, using a custom callback and scrollTo is fine

**Comment by tagliala** [comment]
```coffee
ClientSideValidations.callbacks.form.fail = ($form, eventData) ->
  settings = $form[0].ClientSideValidations.settings
  $('html').animate
    scrollTop: $form.find(".#{settings.html_settings.wrapper_error_class}").offset().top
```

⚠️  This is an example implementation. May require additional checks.
