### ISSUE TITLE
rails.validations.js assumes document.ready event exists

### ISSUE THREAD

**Issue by leebrooks0** [DavyJonesLocker/client_side_validations#554]
I am using CSV with jQuery Mobile and as per http://view.jquerymobile.com/1.3.1/dist/demos/faq/dom-ready-not-working.html
document.ready is not suitable, but CSV makes the assumption that ready() is the ideal event.

I had to edit the asset to the following (at the very bottom)

``` js
  $(document).bind('pageshow', function() {
    ClientSideValidations.disableValidators();
    return $(ClientSideValidations.selectors.forms).validate();
  });

}).call(this);

```

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

CSV will not support jQuery Mobile
