### ISSUE TITLE
Comparison checks do not work with custom seperator and delimiter

### ISSUE THREAD

**Issue by mickiii** [DavyJonesLocker/client_side_validations#559]
Hi, 

I am using the delocalize gem, which works fine when checking numericality and setting ClientSideValidations::Config.number_format_with_locale = true, but when performing subsequent checks, i.e. less_than_or_equal_to, only the input val gets converted according to the local settings, but the check_value does not, which causes the validation to fail.

I have copied the assets to my local asset folder and made a simple workaround:
check_value = check_value.replace(new RegExp("\" + ClientSideValidations.number_format.delimiter, 'g'), "").replace(new RegExp("\" + ClientSideValidations.number_format.separator, 'g'), ".");

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
