### ISSUE TITLE
Combining simple_form and mongoid plugins

### ISSUE THREAD

**Issue by foxandcat** [DavyJonesLocker/client_side_validations#566]
I put both gems into the gemfile like this:

gem 'client_side_validations'
gem 'client_side_validations-mongoid'
gem 'client_side_validations-simple_form'

Simple_form does not validate. form_for does.

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues. I'm using all of them without issues

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
