### ISSUE TITLE
validation generated only for one of two nested simple_field_for

### ISSUE THREAD

**Issue by onlinetocode** [DavyJonesLocker/client_side_validations#568]
Hi there, 

I've got a problem with a multi level nested form on the third level. I've got three models which are involved in my form.

``` ruby
class School < ActiveRecord::Base
  has_many :years
  validates_presence_of :name
  accepts_nested_attributes_for :years
end
```

``` ruby
class Year < ActiveRecord::Base
  belongs_to :school
  has_many :year_contacts
  validates_presence_of :year_name
  accepts_nested_attributes_for :year_contacts
end
```

``` ruby
class YearContact < ActiveRecord::Base
  belongs_to :year
  validates_presence_of :contact_name
end
```

This is my form:

``` erb
<%= form_for @school, :validate => true do |f| %>
  <h4>School</h4>
  <%= f.label 'Name', :class => 'control-label' %>
  <%= f.text_field :name, :class => 'span12', :placeholder => "School name"  %>
  <h4>Year of Graduating</h4>
  <%= f.fields_for :years do |fo| %>
    <%= fo.label 'Year' %>
    <%= fo.text_field :year_name  %>
    <h4>Contact</h4>
    <%= fo.fields_for :year_contacts do |foo| %>
      <%= foo.label %>
      <%= foo.text_field :contact_name %>
    <% end %>
  <% end %>
  <%= f.submit %>
<% end %>
```

The client side validation works like a charm for the school attribute and also for the nested year attribute. But when it comes to the third level nesting it didn't work. There isn't any client side validation for the year_contacts attribute.

I'm not sure if it's a bug, a known limitation of client_side_validations or a error on my side. All known Issues I found were only for two models nested under another model but no true multi level structure like mine. 

I use Rails 3.2.1 and client_side_validations 3.2.5

The form works well. All data is saved as expected.

**Comment by sumanranjanpanda** [comment]
Hi,
I am facing the exact issue. Did you able to fix this issue? 
Please let me know how you fixed this.

Thanks

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

Please note that if simple_form is involved, then the proper repo to report this is --> https://codeclimate.com/github/DavyJonesLocker/client_side_validations-simple_form
