### ISSUE TITLE
Validation of inherited models.

### ISSUE THREAD

**Issue by ruvater** [DavyJonesLocker/client_side_validations#578]
I have Manager model that inherited from Devise user model. I use client-side-validations with simple_forms. 
Manager validations works perfectly on client-side but I didn't find a way to include validations that defined in Devise user model. 

Yes, of course form loads messages of all required validations from @manager.errors.full_messages after pressing a submit button and re-rendering view but I want them to load without applying any actions.

Help, please :)

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

Sorry but I don't know the answer.
