### ISSUE TITLE
validation of uniqueness uses non-existent route after upgrade to 3.2.6

### ISSUE THREAD

**Issue by hau** [DavyJonesLocker/client_side_validations#580]
I just upgraded from 3.2.5 to 3.2.6.  Validation of uniqueness of a field that used to work with 3.2.5 then used a non-existent route after the upgrade.  That caused validation of uniqueness not work at all.

In 3.2.6, the the gem uses a URL `http://localhost:3000/undefinedvalidators/uniqueness?case_sensitive=true&user%5Bemail%5D=tester1%40testsite.net&_=1376995606846` to validate uniqueness.

But in 3.2.5, the gem uses URL
`http://localhost:3000/validators/uniqueness?case_sensitive=true&user%5Bemail%5D=tester1%40testsite.net&_=1376995970259` to validate uniqueness, which works fine.

**Comment by tagliala** [comment]
This should be fixed
