### ISSUE TITLE
Run javascript unit tests on CI

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#591]
At the moment travis is only running ruby related tests (`rake`). There is another suite of tests (`rake test:js`) which only runs locally. I would like to see unit tests run on the cloud. Running on travis with phantom.js is ok, saucelabs would be way better

Anyone can help on this?

TIA

**Comment by reckerswartz** [comment]
How about jasmine for testing e.g https://github.com/searls/jasmine-rails?
