### ISSUE TITLE
DRY Inclusion and Exclusion active model modules

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#593]
https://codeclimate.com/github/bcardarella/client_side_validations/issues/categories/duplication

Tests pass but Is it ok to write:

```
module ClientSideValidations::ActiveModel
  module Inclusion

    include Exclusion

  end
end
```

?

**Comment by bcardarella** [comment]
You could extract out to a more common mixin to mix into both
