### ISSUE TITLE
client_side_validations "4-2-stable" with simple_form

### ISSUE THREAD

**Issue by adham90** [DavyJonesLocker/client_side_validations#594]
i have this error with bundle install.
```
Bundler could not find compatible versions for gem "client_side_validations":
  In Gemfile:
    client_side_validations-simple_form (>= 0) ruby depends on
      client_side_validations (~> 3.2.0) ruby

    client_side_validations (4.2.0)
```
i'm using 'rails', '4.2.0'
what can i do to make client_side_validations-simple_form work with client_side_validations "4-2-stable"??!

**Comment by tagliala** [comment]
please try in your Gemfile
```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form'
```

**Comment by adham90** [comment]
okay, it's bundle fine now, but it didn't effect my forms!!

**Comment by adham90** [comment]
@tagliala this is my project repo
https://github.com/adham90/geekhub

**Comment by tagliala** [comment]
Thank you for reporting this and for your repository.

This is an issue of the simple form gem, I need to check that plugin.

Meanwhile, you can find a workaround here: https://github.com/DavyJonesLocker/client_side_validations-simple_form/issues/38

![image](https://cloud.githubusercontent.com/assets/556268/5845773/1c16b9f4-a1bf-11e4-9b49-0d5a052b6c69.png)
