### ISSUE TITLE
How to override default_scope in mutli-tenant app (with Devise)

### ISSUE THREAD

**Issue by weavermedia** [DavyJonesLocker/client_side_validations#597]
I have `default_scope` on most of my models that scopes by `current_user.company`. I'm using this gem on my sign up page which means there is no tenant set.

When the uniqueness validator runs on `@user.email` the default_scope prevents the validation from running properly (because `company_id` is nil) and therefore always looks like a unique result.

My user model:

```
# user.rb
...
default_scope { where(company_id: Company.current_id) }
...
```

runs this query when validating email:

```
Started GET "/validators/uniqueness?case_sensitive=true& \
user%5Bemail%5D=me%2B40%40example.com&_=1423897339854" \
for 76.175.168.2 at 2015-02-14 07:02:30 +0000                        
  User Exists (0.4ms)  SELECT 1 AS one FROM "users" WHERE \
"users"."company_id" IS NULL AND "users"."email" = 'me@example.com' LIMIT 1
```

When I remove the `default_scope` from my user model I get the correct result and proper validation:

```
Started GET "/validators/uniqueness?case_sensitive=true& \
user%5Bemail%5D=me%2B40%40example.com&_=1423897339854" \
for 76.175.168.2 at 2015-02-14 07:02:30 +0000                        
  User Exists (0.4ms)  SELECT 1 AS one FROM "users" WHERE \
"users"."email" = 'me@example.com' LIMIT 1
```

What's the most practical way for me to override the `default_scope` when this gem runs the email validator?

**Comment by tagliala** [comment]
Thanks for pointing this out. At the moment I'm very busy and I cannot investigate. Any help is really appreciated here

**Comment by weavermedia** [comment]
@tagliala If you point me in the right general direction I'd be happy to help.

I'll take a look at the code in the meantime and see if I can figure it out.

**Comment by tagliala** [comment]
Sorry, never used this gem in this way and I'm also trying to avoid default scopes entirely.

**Comment by tagliala** [comment]
take a look here

http://stackoverflow.com/questions/7212489/rails-3-validate-uniqueness-ignores-default-scope-on-model

**Comment by weavermedia** [comment]
My only idea is that unscoped should be included here:

    # lib/client_side_validations/active_record/middleware.rb
    
    8  def self.is_unique?(klass, attribute, value, params)
    ...
    41   !klass.where(relation).exists?
    42 end
    
    # should this be > !klass.unscoped.where(relation).exists?

Unfortunately I don't yet know how to hack a gem and try out my own version of it. I just spent an hour trying to fork, edit and install my own modification but to no avail. Something else to learn :)

**Comment by tagliala** [comment]
@weavermedia I would really like to help you but I can't at the moment, sorry. Can't also make promises, I'm very busy with my job and life
