### ISSUE TITLE
Validation messages are not showing up

### ISSUE THREAD

**Issue by rdudacz** [DavyJonesLocker/client_side_validations#599]
Hi there,

I am using Rails 4.1.4 and gems in following versions:
```
gem 'turbolinks'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-turbolinks', github: 'DavyJonesLocker/client_side_validations-turbolinks'
```

In `applications.js`:
```
//= require rails.validations
//= require rails.validations.turbolinks
```

and in the view:
```
= form_for(@user, :validate => true) do |f|
```

`bundle` passed well.

But when I test it out, the error (validation) messages never show up. All validation rules are specified in the `User` model.

`config/client_side_validations.rb`:
```
# ClientSideValidations Initializer

# Uncomment to disable uniqueness validator, possible security issue
# ClientSideValidations::Config.disabled_validators = [:uniqueness]

# Uncomment to validate number format with current I18n locale
# ClientSideValidations::Config.number_format_with_locale = true

# Uncomment the following block if you want each input field to have the validation messages attached.
# Note: client_side_validation requires the error to be encapsulated within
# <label for="#{instance.send(:tag_id)}" class="message"></label>
#
ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  unless html_tag =~ /^<label/
    %{<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first}</label></div>}.html_safe
  else
    %{<div class="field_with_errors">#{html_tag}</div>}.html_safe
  end
end
```

I've tried also precompile assets, but without any success.

Any help with what am I missing here?

Thank you, enjoy the weekend!

**Comment by saturnflyer** [comment]
I'm having this same problem. Not really sure what's causing it and I'm still looking into it.
I'm using the code as of 5c1c63e3deb62f1578e1a0b1ad9d4302a4e0fc56 in my rails 4.2 app

**Comment by tagliala** [comment]
I will take a look

btw the turbolinks plugin is not needed anymore, the master branch supports turbolinks out of the box

**Comment by tagliala** [comment]
A reduced test case uploaded on github will speed up my work

**Comment by saturnflyer** [comment]
Looking into this further. I'm still really not sure what happened but it's working for me now.
I had been tweaking the `field_error_proc` and went back to the default. It must have been user error on my part

**Comment by ndran** [comment]
I was having this same issue on my local machine. I quit my rails server ( ctrl + c ), and then ran it again ( rails s ) and it was working. I originally forgot to un-comment the lines in "config/client_side_validations.rb"

**Comment by tagliala** [comment]
Closing here, this should not be an issue anymore or it should be related to conditional validators
