### ISSUE TITLE
Gem Name Conflict

### ISSUE THREAD

**Issue by tsujp** [DavyJonesLocker/client_side_validations#600]
Whilst not really an issue it's not known for a few people to include:

`gem "client_side_validations", github: "DavyJonesLocker/client_side_validations", branch: "master"`

Currently the fetched version, upon including `gem "client_side_validations"` is the old 3.2.6 repo no longer maintained. Can the authors chuck this onto http://rubygems.org/ just for the sake of ease-of-access for those who wouldn't know.

I had a slew of bugs I had to 'solve' before I realised it was using the old 3.2.6 version since this isn't on rubygems.

**Comment by tagliala** [comment]
@tsujp this gem was unmaintained for a long while. 

A lot of things changed, I'm just waiting some more time before releasing a new gem just to make sure there are no major issues

**Comment by tsujp** [comment]
That's a fair point my man. I'm looking forward to it :)

**Comment by tagliala** [comment]
We have 4.2 version for Rails 4.x and 6.0 version for Rails 5.x so we should ok to go
