### ISSUE TITLE
custom validation fails on hidden field

### ISSUE THREAD

**Issue by ivendorin** [DavyJonesLocker/client_side_validations#602]
Hi,

I am trying to do a custom validation but it does not seem to work . Here is my code 

validate :presence_of_inventory_item_id

def presence_of_inventory_item_id
        if self.inventory_item_id.present?
        else
            errors.add(:name, "inventory item not present")
        end
end

in the view 

<%= f.text_field :name %>
<%= f.hidden_field :inventory_item_id %>

**Comment by tagliala** [comment]
Please take a look here: https://github.com/DavyJonesLocker/client_side_validations#custom-validators

**Comment by ivendorin** [comment]
Thanks for your prompt response . I have already checked it and don't think it is different from what i need . I am validating a presence of hidden field and trying to put an error on the name field . Had it not been a hidden field a simple validate :inventory_item_id :presence => true would have worked .

I also tested by adding the message in local and creating a custom js validator file as mentioned in the doc but it is still not validating

**Comment by tagliala** [comment]
could you please provide a repository with the minimum amount of code showing the issue?

**Comment by ivendorin** [comment]
I have written my model and view in brief here https://gist.github.com/ivendorin/3f174fc13c9042fc6227

**Comment by tagliala** [comment]
Sorry but I have few time and the more detail are here the better it is.

Please provide me at least the following details: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue

**Comment by ivendorin** [comment]
I have update the gist please check it again https://gist.github.com/ivendorin/3f174fc13c9042fc6227 

I am using  client_side_validations (4.2.0) and Rails 4.0.1

**Comment by ivendorin** [comment]
here is another gist of htm generated after the validation fails https://gist.github.com/ivendorin/0d7979a638ed4a4eeceb

**Comment by ivendorin** [comment]
Please let me know if you need any other information , if I have not been able to provide sufficient information then please guide me how I can do that . I really need it to make it work 

Thanks,

**Comment by ivendorin** [comment]
If anyone can help me on this it would be great

**Comment by tagliala** [comment]
@ivendorin information are enough for me but unfortunately my time at the moment isn't.

I don't know when I can help you

The best you can do is to provide a repository which reproduces the scenario. Take a look here: https://github.com/DavyJonesLocker/client_side_validations/issues/594#issue-55070646

Of course any help would be really appreciated

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
