### ISSUE TITLE
Getting wrong number of arguments (3 for 2) error with my form_for [Solution: use the master branch]

### ISSUE THREAD

**Issue by Jim2002** [DavyJonesLocker/client_side_validations#603]
I'm getting `wrong number of arguments (3 for 2)` error with my `form_for` 
Does client_side_validations support Rasil 4.1.1  ?
I've been googling, it looks like a lot of people are having the same issue.

**Comment by tagliala** [comment]
@Jim2002 please use version from master branch. The old gem is not supported and I didn't release a new one. I'm having a really busy time, sorry

gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form'

**Comment by tagliala** [comment]
reopening for tracking purposes

**Comment by zenspider** [comment]
Busy for 3 months? Can you please release a fix?

**Comment by tagliala** [comment]
@zenspider meanwhile we have another issue and this is a major release. If I have to drop a feature this is the right moment :)

Please keep using the master branch, sorry

**Comment by sajjadmurtaza49** [comment]
wrong number of arguments (3 for 2)

= form_for @category, validate: true do |f|

**Comment by kjakub** [comment]
hm, bad this is not working

**Comment by tagliala** [comment]
please use the master branch

**Comment by Sharj** [comment]
I had been using this fix for quite some time and it worked. 
Today I tried to setup the project again and it couldn't install the gem using 

`gem 'client_side_validations' , github: 'DavyJonesLocker/client_side_validations'`

Error while doing `bundle install`

`NoMethodError: undefined method 'spec' for nil:NilClass`
`An error occurred while installing client_side_validations (4.2.0), and Bundler cannot continue.`

While 
`gem 'client_side_validations'` works but then it gives the same error  `wrong number of arguments (3 for 2)`

I am using `Ruby 2.1.5` and `Rails 4.2.3`

**Comment by tagliala** [comment]
CSV 4.2.0 released :)
