### ISSUE TITLE
Gem installation causes error: number of arguments (3 for 2)

### ISSUE THREAD

**Issue by reconstructions** [DavyJonesLocker/client_side_validations#604]
When I install version 3.2.6 of this gem with Rails 4.2.0, run `bundle install`, require `rails.validations` in my `application.js`, and restart my server, I get the following error from the first line of all my forms: `wrong number of arguments (3 for 2)`.  My typical form signature looks like this:

`= form_for(song, html: {class: "fields-form" }) do |f|`

I also tried changing to vanilla form signatures and that didn't fix it.  I can repeat and fix the error by adding or removing the gem and the javascript 'require' statements.

Thanks in advance!

**Comment by tagliala** [comment]
https://github.com/DavyJonesLocker/client_side_validations/issues/603#issuecomment-78965071

**Comment by reconstructions** [comment]
Sorry, this other issue posting must have gone up after I took a look at existing issues but before I finished writing my post.

**Comment by tagliala** [comment]
@reconstructions don't worry, that is because I closed the previous one
