### ISSUE TITLE
Release a gem version?

### ISSUE THREAD

**Issue by bdmac** [DavyJonesLocker/client_side_validations#610]
Just trying to figure out what's going on w/development on this gem. There appears to be active work happening but the latest released gem version is 3.2.6 and it's way outdated. Are there any plans to release an updated version of this gem in the near future or should we just run against master (ick)?

**Comment by tagliala** [comment]
yes, it is planned but I'm having little time. 

Leaving this open for tracking purposes

**Comment by douglasmiller** [comment]
Do you have any ETA for the 4.2 version to be released to rubygems? I'd like to use this in a Rails 4.2 project, but I'm unwilling to include a unstable gem.

**Comment by tagliala** [comment]
@douglasmiller at the moment I really can't. There is something in this gem that I probably need to do before releasing this gem that will probably break things

**Comment by tagliala** [comment]
Done!

**Comment by douglasmiller** [comment]
Fantastic news! Thanks!

**Comment by tagliala** [comment]
I'm just waiting for Brian enable me so I can also release simple form and mongoid plugins
