### ISSUE TITLE
Does not work on BootStrap Modal Boxes

### ISSUE THREAD

**Issue by xrimpy** [DavyJonesLocker/client_side_validations#611]
Trying to figure out a solution, myself

**Comment by tagliala** [comment]
maybe you just need 

https://github.com/DavyJonesLocker/client_side_validations#enabling

> You can use the same function if you introduce new inputs to an existing form:
 `$(new_input).enableClientSideValidations();`

something like:
```coffee:
$(document).on 'show.bs.modal', '#my-modal', ->
  $('#my-modal-form').enableClientSideValidations()
```

**Comment by xrimpy** [comment]
I am not using AJAX modal boxes

But still tried, to make sure no code is conflicting I have setup a fresh minimal Rails project (4.2)

with Boostrap 3.3.4 install through bower


Following is the form

	    <%= form_for Yo.new, validate: true do |f| %>
			  <div class="field">
			    <%= f.label :title %><br>
			    <%= f.text_field :title %>
			  </div>
			  <div class="actions">
			    <%= f.submit %>
			  </div>
			<% end %>

If I extract the form out of the modal box everything works

Tried disabling validations on the extracted form

		<script type="text/javascript">
		 	 $('#new_yo').disableClientSideValidations();
		 	//THIS DOES NOT WORK, no


			$('#boots').on('shown.bs.modal', function () {
				   $('#new_yo').enableClientSideValidations();
				  // alert("Hello"); just checking
				})
     	</script>


The following is the HTML generated by the form

form method="post" accept-charset="UTF-8" action="/yos" id="new_yo" class="new_yo" novalidate="novalidate" data-validate="true"

**Comment by tagliala** [comment]
@xrimpy the problem is that CSV doesn't enable itself on hidden fields, so if they are showed within a modal you should run the above js code. 

If you can provide me a working example and push the code on github I can take a look

**Comment by xrimpy** [comment]
You can find the code at

https://github.com/xrimpy/bootstrapcsv

Thanks for the pointers, I understand the BS.modal logic

I think I am unable to connect the disableClientSideValidations

The following does not work

$(new_yo).disableClientSideValidations(); 

I tried

$('.new_yo').disableClientSideValidations(); 
$('#new_yo').disableClientSideValidations(); 

No luck

**Comment by tagliala** [comment]
Don't know what to do here:

![screen shot 2015-04-06 at 18 38 51](https://cloud.githubusercontent.com/assets/556268/7007658/3a2425c8-dc8c-11e4-8821-d2056a361dcb.png)

**Comment by spawnge** [comment]
+1 ! I have the exact same problem. When I do this:
```
$(document).ready(function(){
$(document).on('show.bs.modal', '#my-sign-up-modal', function(){
  console.log("test");
  $('document').find("form#sign-up").enableClientSideValidations();
})
})
```

it doesn't add client side validations so my form and I can see "test" in my console. However if I directly type `$('document').find("form#sign-up").enableClientSideValidations();` in the console validations work. This is so frustrating does anyone have a suggestion/solution ?

**Comment by tagliala** [comment]
@spawnge could you please fix  the above repository so I can take a look?

**Comment by spawnge** [comment]
@tagliala I tried to recreate the issue (https://github.com/spawnge/modal-client) but it's actually working fine. The problem was that I had tabs in my modal so I had to use the shown.bs.tab event handler (and I needed some sleep too !). sorry for the false alert.

**Comment by tagliala** [comment]
do not worry, glad you solved! :+1:

**Comment by tagliala** [comment]
@spawnge if you could confirm that there are no issues inside a bootstrap modal, given that a proper javascript is executed to enable validations on new elements, I will close this one

**Comment by spawnge** [comment]
I had no issue with the bootstrap modal you can try it here https://github.com/spawnge/modal-client however I'm using simple form so I'm not a 100% sure it is working with normal forms.

**Comment by xrimpy** [comment]
Works

Here is a link to a working Bootstrap rep without simple form

https://github.com/xrimpy/bootstrapcsv


I could not get to the core of the problem, my machine crashed I set up a new machine and it just worked.


Thank you very much.

**Comment by tagliala** [comment]
@xrimpy you're welcome, glad you solved :+1:

**Comment by kobaltz** [comment]
For documentation & future reference, this is my solution. 

```
  # coffeescript
  $('.modal').on 'shown.bs.modal', ->
    $('form[data-validate]').enableClientSideValidations()
```

```
//jquery
$('.modal').on('shown.bs.modal', function() {
  $('form[data-validate]').enableClientSideValidations();
});
```

**Comment by tagliala** [comment]
@kobaltz feel free to add a page to the wiki https://github.com/DavyJonesLocker/client_side_validations/wiki

**Comment by salmagomaa** [comment]
@kobaltz thanks a million for documenting the solution
