### ISSUE TITLE
Simple suggestion how to break brute attack on uniqueness filter 

### ISSUE THREAD

**Issue by alekseyl** [DavyJonesLocker/client_side_validations#612]
Uniqueness validators are possibility for brute attack. 
What do you think on making some monkey patch like this: restricting frequency for request to be made from one IP. Something like: fist five - immediately, second five - not faster than one in second, third five - not faster than in 2 secs, fourth five - five seconds per request. 

It changes code on both side on server side you will give response wait N sec untill next, in JS you made a timer on that amount of secs, and possibly some ticking tooltip ( too much requests from your IP are made, your next attempt will be in a X sec ).

This will make bruteforce practically impossible from one machine, and very hard for a network of such.

What do you think of that?

**Comment by tagliala** [comment]
Hi,

in the next commit on the master branch I will disable the uniqueness validator by default.

AFAIK, on the server side there are options like https://github.com/kickstarter/rack-attack and https://github.com/sinatra/rack-protection

I prefer to remove this feature at all, leaving the implementation to the user because.

Giving that, PR with client side support rack-attack/rack-protection errors are welcomed

**Comment by dm1try** [comment]
@tagliala +1 for disabling by default, anyway the user will be aware about security issues if he deicide to enable this middleware. 
BTW `rack-attack` is a good choice for those situations!

**Comment by tagliala** [comment]
The disable by default commit is on its way.

If you don't use uniqueness at all, I suggest to completely unload the middleware.

```rb
ClientSideValidations::Engine.config.app_middleware.delete ClientSideValidations::Middleware::Validators```

A PR that conditionally loads the middleware only if needed is very welcomed

**Comment by tagliala** [comment]
Feel free to comment here or submit a PR if there are any mistakes (I'm not an English native speaker)

https://github.com/DavyJonesLocker/client_side_validations/commit/698022655c90cc581f113aa0a49f545c13c94a9d

**Comment by tagliala** [comment]
@alekseyl I'm thinking about to completely remove the uniqueness middleware because of this brute force attacks.

Any improvement to the readme (eg: if you enable this feature you should use rack-attack to mitigate brute force attacks... etc.) is very welcomed
