### ISSUE TITLE
Regex in generated script differs from regex in model

### ISSUE THREAD

**Issue by adekbadek** [DavyJonesLocker/client_side_validations#615]
Hi, I have a format validation in my user model to allow all letters (non-latin too), numbers, dashes and underscores:
  validates_format_of :username, :with => /\A[\p{L}0-9\\-\_\s]+\z/
Non-latin chars pass the server-side validation, however the client-side shows errors. I looked at the script generated under the form and it has the following regex:
  ^[\\\p{L}0-9\\\\-_\\\s]+$
which means something different

**Comment by tagliala** [comment]
Hi,

javascript does not support \A and \Z.

It seems there is a bug here. I need to take a look

**Comment by thenadz** [comment]
There's another issue that fits this title so adding here...

Regexes are being stripped of spaces. For example, `/\A\s*(?:\+?(\d{1,3}))? ([-. (]*(\d{3})[-. )]*)?((\d{3})[-. ]*(\d{2,4})(?:[-.x ]*(\d+))?)\s*\z/` (international phone number) becomes `^\s*(?:\\+?(\\d{1,3}))?([-.(]*(\\d{3})[-.)]*)?((\\d{3})[-.]*(\\d{2,4})(?:[-.x]*(\\d+))?)\\s*$`.

**Comment by tagliala** [comment]
Fixed via #637
