### ISSUE TITLE
broken logic

### ISSUE THREAD

**Issue by alekseyl** [DavyJonesLocker/client_side_validations#619]
Hi there.

I think you broke the logic of conditional validation here:

https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model.rb

```
  else result = can_force_validator?(attr, validator, force)
        if validator.options[:if]
          result = result && run_conditional(validator.options[:if])
        end
        if validator.options[:unless]
          result = result && !run_conditional(validator.options[:unless])
        end
      end
```

So it's looks like you wanted either: 

result = result || run_conditional(validator.options[:if])

OR 

elsif result = can_force_validator?(attr, validator, force)

so it will make sense because if you get FALSE here: result = can_force_validator?(attr, validator, force), you'll get false everywhere down the scope of else.

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
