### ISSUE TITLE
Conditional validators firing

### ISSUE THREAD

**Issue by MitchellGeere** [DavyJonesLocker/client_side_validations#623]
I am using conditional validations on app that all work sans client_side_validations but not with. I don't get any exceptions, I tried to follow the path to see if there is a silent error but nothing, it is simply not picking up the fields that need to be conditionally validated. (client_side_validations works great for the non-conditional ones!)

I tried with the sources below and none worked - at least there is consistency :)

```ruby
gem 'client_side_validations'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: "4-2-stable"
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: "master"
```

Some Code: 

The Model
```ruby
validates :start_at_time, presence: true, if: :is_open?

def is_open?
    true   #so it should always work, I made it true for testing
end
```
The View
```erb
<%= f.text_field :start_at_time, validate: true  %>
```
The Rendered View
```html
<input placeholder="00:00" type="text" name="calendar_item[start_at_time]" id="calendar_item_start_at_time">
```
The one difference between the conditional fields and others is that the conditional fields don't have the `data-validate="true"` attribute on them even though I set `validate: true` in the view / erb.

I am running the following
```terminal
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
Rails 4.2.0
```

**Comment by tagliala** [comment]
as a workaround, try with `presence: { if: :condition? }`

**Comment by tagliala** [comment]
I cannot confirm. Are you using any particular form builder? Could you please provide a repo showing your issue? 

Please take a look at: https://github.com/tagliala/csv-test

Relevant commit: https://github.com/tagliala/csv-test/commit/18c11b50b9976825f3f311c9052fb46987410435

![screen shot 2015-07-01 at 14 07 57](https://cloud.githubusercontent.com/assets/556268/8454058/ae869d9a-1ffa-11e5-861d-b81a34cc8823.png)

Meanwhile... closing here

**Comment by MitchellGeere** [comment]
my apologies for the late reply. 

I'm not using any particular form builder other than what comes with Rails 4.2 no DSL's etc. just straight ERB's using an unmodified FormBuilder from ActionView::Helpers.

However ran your example and it worked just fine. 

I updated my rails to match yours (that was the only difference) and tried running again and it only worked on some fields (condition is the same) and it only worked if I left the back and came back. So I am really just stumped. I need to investigate. This does however feel like 100% an environment problem. Thanks for the help.

**Comment by MitchellGeere** [comment]
UPDATE

The culprit was turbolinks. This fixed my problem:

```
javascript
$(document).on('page:load', function () 
{
   // code here
});
```

I hide the field until the user checks a checkbox then I reveal it (display: block vs display: none) at which it should be validated. Javascript just never got to it, now it does. Thanks for the help Geremia (@tagliala)

**Comment by tagliala** [comment]
You're welcome, glad you solved

**Comment by MitchellGeere** [comment]
Even though I got it all working nicely in one case I still couldn't get it working in another. I didn't think it was part of an issue so I posted it on Stackoverflow.

http://stackoverflow.com/questions/31236809/validate-the-presence-of-a-value-in-another-field-using-client-side-validations
