### ISSUE TITLE
Add collection_radio_buttons and collection_check_boxes helpers

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#624]
There are some new helpers in Rails 4, such as

* http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_radio_buttons
* http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormBuilder/collection_check_boxes

csv should deal with the above methods

**Comment by rohaldb** [comment]
I am struggling to get this to work. Ive tried adding `validates_presence_of  :interest_ids` to ensure that at least one checkbox in a `collection_check_boxes` of interest is selected, but it didnt work. Then i tried to add a custom validator but the custom validator in  `rails.validations.customValidators` was never triggered. How do i use this properly?

**Comment by tagliala** [comment]
@rohaldb

feel free to start a new issue

Please keep in mind that investigating CSV issues is a time consuming task. Please provide all the information required by the [Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue), but a reduced test case pushed to github would be hugely appreciated. Example: https://github.com/ghaydarov/CSV-CW
