### ISSUE TITLE
server side validation is not getting triggered (mongoid)

### ISSUE THREAD

**Issue by adityashankert** [DavyJonesLocker/client_side_validations#626]
when using client_side_validations with mongoid the remote validation is not getting triggered
versions : 
  client_side_validations : 4.2.0
  mongoid : 4.0.2

model code 
```
class User
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
field :email, type: String
....
validates :email, :presence =>{message: "email cannot be blank"},
           format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
                     message: 'Please enter a valid email'}
validates_uniqueness_of :email
....
end
```

form code
```
<%= form_for @organisation, url: organisations_signup_save_path,validate: true do |org| %>
......
<%= org.fields_for :users do |user| %>
     <%= user.text_field :email, validate: true %>
<% end %>
......
<% end %>
```
script code
```
//<![CDATA[
if(window.ClientSideValidations===undefined)window.ClientSideValidations={};window.ClientSideValidations.disabled_validators=["uniqueness"];window.ClientSideValidations.number_format={"separator":".","delimiter":","};if(window.ClientSideValidations.patterns===undefined)window.ClientSideValidations.patterns = {};window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/;if(window.ClientSideValidations.forms===undefined)window.ClientSideValidations.forms={};window.ClientSideValidations.forms['new_organisation'] = {"type":"ActionView::Helpers::FormBuilder","input_tag":"\u003cdiv class=\"field_with_errors form-group has-error\"\u003e\u003cspan id=\"input_tag\" /\u003e\u003clabel for=\"\" class=\"message control-label\"\u003e\u003c/label\u003e\u003c/div\u003e","label_tag":"\u003cdiv class=\"field_with_errors form-group has-error\"\u003e\u003clabel id=\"label_tag\" /\u003e\u003c/div\u003e","validators":{"organisation[users_attributes][][fullname]":{"presence":[{"message":"Name cannot be blank"}]},"organisation[users_attributes][][email]":{"presence":[{"message":"email cannot be blank"}],"format":[{"message":"Please enter a valid email","with":{"source":"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]+$","options":""}}],"uniqueness":[{"message":"translation missing: en.mongoid.errors.models.user.attributes.email.uniqueness"}]},"organisation[users_attributes][][username]":{"presence":[{"message":"Username cannot be blank"}],"uniqueness":[{"message":"translation missing: en.mongoid.errors.models.user.attributes.username.uniqueness"}]},"organisation[users_attributes][][licence_number]":{"presence":[{"message":"MCA Licence no. cannot be blank"}]},"organisation[name]":{"presence":[{"message":"Hospital Name cannot be blank"}]},"organisation[terms]":{"acceptance":[{"message":"Terms and Conditions must be accepted","accept":"1"}]}}};
//]]>
```

**Comment by tagliala** [comment]
>  the remote validation is not getting triggered

It is fine because the remote uniqueness validator is disabled by default because of security concerns and will be probably removed before the final release of 4.2.0 version

From readme: https://github.com/DavyJonesLocker/client_side_validations#security

Let me know

**Comment by adityashankert** [comment]
it is working now and if you remove in the final release how can we get that functionality hope there will be some way to write custom implementation when you remove it fully as it very important feature although there is security issue.

**Comment by adityashankert** [comment]
And now the issue is i'm getting 500 error

**Comment by tagliala** [comment]
The idea is to extract the remote validators in a plugin (that I will not maintain). More info here: #612

**Comment by adityashankert** [comment]
@tagliala now im getting 500 error :(

**Comment by adityashankert** [comment]
So I went through the code as I saw it is raising exception because I am using mongoid . Can you please tell me how to override that is_unique? function

**Comment by tagliala** [comment]
That's because you probably need https://github.com/DavyJonesLocker/client_side_validations-mongoid that is not up to date.

I will update that plugin too

**Comment by adityashankert** [comment]
But I cant use it now as it has some lock with mongoid version can you fix those basic things so that I can use it by when can we expect your update? and let me know if you want any help I will also contribute to it :) ... For now I am overwriting the is_unique? method for now let me know when it is updated I will start using it.

**Comment by tagliala** [comment]
Feel free to fork that project but I'm working on it.

**Comment by tagliala** [comment]
https://github.com/DavyJonesLocker/client_side_validations-mongoid/tree/mongoid4

There are 2 failing specs, PR are welcomed

**Comment by tagliala** [comment]
All specs pass, please give a try

```rb
gem 'client_side_validations-mongoid', github: 'DavyJonesLocker/client_side_validations-mongoid', branch: 'mongoid4'
```

**Comment by tagliala** [comment]
@adityashankert any news? Can I merge mongoid4 branch with master?

**Comment by adityashankert** [comment]
I will check tomorrow morning and let u know was busy with something else

**Comment by tagliala** [comment]
ok, thanks!

**Comment by adityashankert** [comment]
It is still going to active record validator and returning 500 should I need to do something which will make it look for mongoid validator class or it will automatically work?

**Comment by tagliala** [comment]
could you please post your gemfile?

**Comment by adityashankert** [comment]
Gemfile details for mongoid validations

```
gem "mongoid"
.....
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-mongoid', github: 'DavyJonesLocker/client_side_validations-mongoid', branch: 'mongoid4'
```

**Comment by tagliala** [comment]
Working here

Sample repo: https://github.com/tagliala/csv-test-mongoid

**Comment by tagliala** [comment]
![screen shot 2015-07-14 at 09 44 55](https://cloud.githubusercontent.com/assets/556268/8668601/0ae1855c-2a0d-11e5-8991-1b310e7c46c4.png)

Closing here but feel free to comment

**Comment by adityashankert** [comment]
Can you explain me how you are detecting which middleware to look for ClientSideValidations::Mongoid or ClientSideValidations::ActiveRecord? because I use activerecord and mongoid both in my application...

**Comment by tagliala** [comment]
Sorry, never used this gem in that way.

Let me know if you have news

**Comment by adityashankert** [comment]
So as far as I have observed gem is deciding which core it should used based on if that component is defined in [client_side_validations.rb](https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations.rb) but it will only work if we are using one type of orm but if I use multiple orm's i.e., mongoid,active_record in same app it won't work instead of this if we move the logic to middleware where we check which type of model we are dealing and interact with that orm and merge all the gems so that it will be easy to manage and we can gain more granular control. This is my view if you want we can discuss more on this.

**Comment by tagliala** [comment]
This could be a great chance to completely remove this middleware from the gem, as I intended to do

Are you available to maintain this feature in a separate repository?

**Comment by adityashankert** [comment]
Sure thing but only on weekends I can contribute fully.... Is it ok?

**Comment by tagliala** [comment]
it is ok for me
