### ISSUE TITLE
client side validations gem cant install with client side validations mongoid

### ISSUE THREAD

**Issue by SupremeA** [DavyJonesLocker/client_side_validations#627]
I am trying to install the gem 

    gem 'client_side_validations-mongoid', github: 'DavyJonesLocker/client_side_validations-mongoid', branch: 'mongoid4'

This gem is dependent on client_side_validations version 4.2.0
When I bundle it cant find the 4.2.0 version

I saw your update to the mongoid add-on gem but that requires client_side_validations 4.2.0. When I try to install that version it cant seem to find it. 

Can you either remove the version requirement or change the gem to accept 4.2.0 or greater?

**Comment by tagliala** [comment]
you should use
```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
gem 'client_side_validations-mongoid', github: 'DavyJonesLocker/client_side_validations-mongoid', branch: 'mongoid4'
```

**Comment by SupremeA** [comment]
That got it! Thanks!

**Comment by tagliala** [comment]
You're welcome!

I don't know when I will release a new gem, but it would take a while
