### ISSUE TITLE
Not working anymore with reform 2.0.0 and newer

### ISSUE THREAD

**Issue by FelipeKoblinger** [DavyJonesLocker/client_side_validations#628]
Hello! The latest version of reform gem (2.0.0 and newer) isn't working anymore with Client Side Validations (tested with latest git commit 4f43c922f2065054bba2cd56965270c81c4347be). The script tag comes empty in validators hash.

I've found two solutions (thanks @niedhui for the help). First was to add `client_side_validation_hash` method to `Reform::Form` instance. I've made a initializer file containing the code below:

```ruby
Reform::Form.class_eval do
  include Reform::Form::ActiveModel::Validations

  def client_side_validation_hash(force = nil)
    self.model.client_side_validation_hash(force)
  end
end
```

Second was inside gem code. I've made it work adding a condition inside `construct_validators` method to verify if `object_opts[0]` was a `Reform::Form` and assigning `object_opts[0]` as model from `Reform::Form` object.

`action_view/form_helper.rb#L87`
https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/action_view/form_helper.rb#L87

``` ruby
def construct_validators
  @validators.inject({}) do |validator_hash, object_opts|
    option_hash = object_opts[1].inject({}) do |option_hash, attr|
      option_hash.merge!(attr[0] => attr[1][:options])
    end

    # Support reform gem 2.0.0 and newer (probably not working for lower versions)
    if object_opts[0].is_a?(Reform::Form)
      object_opts[0] = object_opts[0].model
    end

    if object_opts[0].respond_to?(:client_side_validation_hash)
      validation_hash = object_opts[0].client_side_validation_hash(option_hash)
    else
      validation_hash = {}
    end

    option_hash.each_key do |attr|
```

After one of those, Client Side Validations started working again. Should be nice if we get support for reform 2.0.0 and newer in Client Side Validations :smile:

--
Version Client Side Validations: commit 4f43c922f2065054bba2cd56965270c81c4347be
Version of Rails: 4.2.3

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

I'm not going to include gem-specific code in the main client side validations repo

you could start e new plugin forking this one: https://github.com/DavyJonesLocker/client_side_validations-simple_form

Let me know if you are interested

**Comment by FelipeKoblinger** [comment]
I've never made a gem before. But I can try :)
I need to do anything special after forking?

**Comment by tagliala** [comment]
feel free to ask if you need more info

you should fork, rename (something like replacing `SimpleForm` with `Reform` and `simple_form` with `reform`), reset version number, replace existing code with your own code, fix tests, publish the gem to rubygems

I'm using appraisal for testing the gem against multiple rails versions. Info here: https://github.com/thoughtbot/appraisal

Guides:
http://guides.rubygems.org/make-your-own-gem/
http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

**Comment by tagliala** [comment]
Closing here but feel free to comment

**Comment by cmolenda** [comment]
Given that I'm using rails, this one line work around did it for me:

_config/initializers/reform_with_client_side_validations.rb_
`Reform::Form.delegate :client_side_validation_hash, to: :model`
