### ISSUE TITLE
is twitter typeahead conflicts client side validation? (CSV 3.0)

### ISSUE THREAD

**Issue by nishanthan144** [DavyJonesLocker/client_side_validations#629]
I am using [client side validation](https://github.com/DavyJonesLocker/client_side_validations)(v3.0.13) gem in my rails(v3.0.20) app. Recently I added [twitter's typeahead.js](https://github.com/twitter/typeahead.js/)(v0.10.2) for auto suggest. 

I have a model named Insurance and the column 'name' is mandatory. When I submit a form with these two js files loaded, I get javascript error **Cannot read property 'presence' of undefined** in browser console. After this error, other javascript code is failed to run, for example If I put a alert in form submit function, its not working.

Model 

insurance.rb

```
    class Insurance < ActiveRecord::Base
        validates :name, :presence =>  { :message => "Must be filled" }
    end
```

form.html.erb

```
    <%= javascript "rails.validations", "typeahead" %>
    <%= stylesheet "typeahead"%>

    <%= form_for @insurance, :validate => true, :html => {:id => 'insurance_form', :class=>"form-horizontal"} do |f| %>
    <div class="control-group">
        <%= f.label :name, :class=>"control-label" %>
        <div class="controls">
            <%= f.text_field :name, :class =>"input-medium typeahead" %>
        </div>
    </div>
    ...
    <% end %>
```

And my javascript code

```
    var insurance_names = ["aaa", "bbb", "ccc"];

    var substringMatcher = function(strs) {
      return function findMatches(q, cb) {
        var matches, substringRegex;
        matches = [];
        substrRegex = new RegExp(q, 'i');
        $.each(strs, function(i, str) {
          if (substrRegex.test(str)) {
            matches.push({ value: str });
          }
        });     
        cb(matches);
      };
    };

    $('.typeahead').typeahead({
      hint: true,
      highlight: true,
      minLength: 1
    },
    {
      name: 'insurance_names',
      displayKey: 'value',
      source: substringMatcher(insurance_names)
    });
```

If I comment the model validation code and then submit the form, then there is no javascript error. 
And also without this typeahead.js client side validation is working fine.

Here's the POST request that fires when I submit the form:

```
Started POST "/insurances" for 127.0.0.1 at 2015-07-28 18:31:53 +0530 Processing by InsurancesController#create as HTML Parameters: {"utf8"=>"✓", "insurance"=>{"insurance_name"=>"", "description"=>""}, "commit"=>"Create insurance"}

....

Rendered insurances/new.html.erb within layouts/nhs-full (209.4ms) Completed 200 OK in 8333ms (Views: 218.3ms | ActiveRecord: 84.5ms) 
```

Can anyone help me to solve this problem?

**Comment by tagliala** [comment]
Sorry, your version is no longer supported. I will not take a look but I will leave this issue open.

Even if the issue is still present on the master branch and we manage to fix this, I will not backport the fix to 3.0 branch

**Comment by FelipeKoblinger** [comment]
Hello! I don't know if this helps, but I've a problem when using typeahead too.
I'm using latest (-1) version of Client Side Validations (commit f819f7c769d3876fe00926301a037dae28276ed1) with Rails 4.2.6 and Ruby 2.3.0.

I guess this is because Typeahead creates an extra input element that is not hidden (but you can't see it). When form is submitted, the Client Side Validations tries to validate it, but this input has no attribute name, jQuery can't find element name and throws ```undefined``` as result, then the error occurs because of no ```search``` method.

Image example:
![InputElement](http://i67.tinypic.com/kcdxzl.png)
* The second input is the real one.

*** When the error occurs, the form is sent bypassing the validations. 

**Error**: ```TypeError: undefined is not an object (evaluating 'element.attr('name').search')```

```javascript
if (element.attr('name').search(/\[([^\]]*?)\]$/) >= 0) {
  destroyInputName = element.attr('name').replace(/\[([^\]]*?)\]$/, '[_destroy]');
  if ($("input[name='" + destroyInputName + "']").val() === "1") {
    passElement();
    return afterValidate();
  }
}
```

For quick fix I've wrapped this block verifying if not undefined.

```javascript
if (element.attr('name') !== undefined) {
    if (element.attr('name').search(/\[([^\]]*?)\]$/) >= 0) {
        destroyInputName = element.attr('name').replace(/\[([^\]]*?)\]$/, '[_destroy]');
        if ($("input[name='" + destroyInputName + "']").val() === "1") {
            passElement();
            return afterValidate();
        }
    }
}
```

Hope this help :)

**Comment by tagliala** [comment]
@FelipeKoblinger thanks. Could you please consider submitting a PR and a failing test case?

BTW I would go for
```coffee
if element.attr('name')? && element.attr('name').search(/\[([^\]]*?)\]$/) >= 0
```

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
