### ISSUE TITLE
Validation is not working

### ISSUE THREAD

**Issue by sajjadmurtaza49** [DavyJonesLocker/client_side_validations#635]
In Model 
 validates :category_name, presence: true

In Form 

  = form_for @category, validate: true do |f|
    div class="col-xs-4"
      = f.label :category_name
      = f.text_field :category_name,:placeholder => "Electronics" , class:"form-control"

Application Js
 //= require rails.validations

__________________________Initializer

ClientSideValidations::Config.disabled_validators = [:uniqueness]

 ClientSideValidations::Config.number_format_with_locale = true

ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  unless html_tag =~ /^<label/
    %{<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first}</label></div>}.html_safe
  else
    %{<div class="field_with_errors">#{html_tag}</div>}.html_safe
  end
end

I am using gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'

**Comment by sajjadmurtaza49** [comment]
This was dua to morris js

**Comment by tagliala** [comment]
Thanks :+1:
