### ISSUE TITLE
Allow a re-load of the client side validations

### ISSUE THREAD

**Issue by AJFaraday** [DavyJonesLocker/client_side_validations#639]
I've been working with client side validations in rails 3.0 and discovered that there was no simple way to add validations to any asynchronously loaded forms. (I've had a quick look at the master branch and it doesn't appear to be possible there.

Locally, I've saved the function at the top of the file in a varable named `clientSideValidationInit` and added this method for removing existing callbacks and re-initialising the client side validation. 

```javascript
reloadClientSideValidations = (function() {
  jQuery('form[data-validate]').find('[data-validators]input')
    .unbind('element:validate:after')
    .unbind('element:validate:before')
    .unbind('element:validate:fail')
    .unbind('element:validate:pass')
  ;
  clientSideValidationInit(jQuery);
});
```

This may not be the best approach, but I'd like to see a way to re-init the client side validation, or fill in missing callbacks for async fields.

**Comment by AJFaraday** [comment]
(I appear to be unable to add labels to this, but it should probably have 'feature request' and 'javascript')

**Comment by tagliala** [comment]
Does this wiki help?

https://github.com/DavyJonesLocker/client_side_validations/wiki/Validating-dynamically-added-forms

**Comment by AJFaraday** [comment]
It does, now I've moved up a version.
