### ISSUE TITLE
Rails 4.2.2 not responding

### ISSUE THREAD

**Issue by doz87** [DavyJonesLocker/client_side_validations#640]
I've installed the gem as per the instructions, the app is not responding at all to it.
The only thing I can think of is that I'm running Rails 4.2.2 and it looks like the gems version is only up to 4.2.0

**Comment by paulolieuthier** [comment]
@doz87 what was the problem? How did you fix it?

**Comment by tagliala** [comment]
@paulolieuthier this should not be a problem anymore

**Comment by paulolieuthier** [comment]
Yeah, I just figured I had to restart the rails server after installing the gem. Stupid. :)
