### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#645]
- [x] Make all ruby tests pass
- [x] Make all javascript tests pass
- [x] Use Method#prepend instead of alias_method_chain
- [x] Add javascript support for case insensitive confirmation validator
- [x] Wait for a `rack >= 2.0.0` compatible version of Sinatra

**Comment by tagliala** [comment]
It should be done, please giva a try to

```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5'
```

**Comment by SebDE** [comment]
It worked perfekt for me - many thanks ! Just no problem with the simple-form-plugin (only small deprecated warning)

**Comment by tagliala** [comment]
@SebDE 'cause the simple-form plugin still makes use of `alias_method_chain`, I will start a new branch there

**Comment by arturtuii** [comment]
Single error was found in the form submit when validating the first time and an error occurs, it is not possible to send the form again

**Comment by tagliala** [comment]
does this happen only on rails5?

**Comment by SebDE** [comment]
@arturtuii can you post a example of the behaviour or the code - i just tested with my application (under Rails 5) and I'm able to submit the form every time without problems - if there are no validation errors.

**Comment by arturtuii** [comment]
Found error now, occurred in rails.validations.custom. This working perfectly, very good this release.

**Comment by tagliala** [comment]
glad to hear that :+1:

**Comment by kobaltz** [comment]
I found that I had to add

```
document.addEventListener("turbolinks:load", function() {
  ClientSideValidations.disableValidators();
  return $(ClientSideValidations.selectors.forms).validate();
})
```

after `rails.validations` and after `turbolinks` loads.

**Comment by tagliala** [comment]
@kobaltz this is about Turbolinks 5? Could you please open a new request and provide a failing test case or an application with step-to-step to reproduce?

**Comment by kobaltz** [comment]
@tagliala, that is correct. I was using `turbolinks 5.0.0beta2`. I can provide an example app or steps to reproduce, but it was a new application with only one model that I was testing with. 

Typically with using Turbolinks 5 from an upgraded 2.3 application, you could add the compatibility include to translate the `page:load` to `turbolinks:load`. Since Rails 5 ships with Turbolinks 5, this would be necessary. https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee

**Comment by tagliala** [comment]
@kobaltz a new test application with step-by-step guide to reproduce hosted on github would be enough

**Comment by kobaltz** [comment]
Example App: https://github.com/kobaltz/csv-example

Here is the example app. 

My steps to reproduce

```
: 1465141516:0;rails new csv-example
: 1465141524:0;cd csv-example
: 1465141538:0;rails g scaffold users first_name last_name age:integer
: 1465141544:0;rake db:migrate
- adds client_side_validations gem pointing to the rails5 branch
: 1465141577:0;subl .
: 1465141605:0;bundle
: 1465141616:0;rails g client_side_validations:install
: 1465141626:0;rails g client_side_validations:copy_assets
```

In the user model

```
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
end
```

And the form

`<%= form_for(user, validate: true) do |f| %>`


If you start the application and try to create a new user (leaving the form fields blank, you'll notice the error message populated from `user.errors.any?` which means that the request has posted back to the users controller and that rails is handling the validations. If you were to refresh the page once you go to the users#new, it will load the `rails.validations` appropriately and posting a blank form will be handled by the client side validation. 

This occurs because 658-661 of `rails.validations` looks like

```
$(document).bind((window.Turbolinks ? 'page:change' : 'ready'), function() {
    ClientSideValidations.disableValidators();
    return $(ClientSideValidations.selectors.forms).validate();
  });
```

where `page:change` should be `turbolinks:load`.

However, this would be a breaking change for those using turbolinks-classic.

I'm really just documenting this for future reference of those who may run into the same issue.

**Comment by tagliala** [comment]
Thanks, I will take a look asap

**Comment by tagliala** [comment]
I'm going to consider Turbolinks 5 off topic for this issue because Turbolinks 5 also works for Rails 4 and the current implementation is bugged.

Please use #661

**Comment by tagliala** [comment]
@kobaltz please take a look here: https://github.com/DavyJonesLocker/client_side_validations/issues/661#issuecomment-225906191

I'm going to test against IE8, add this change to the 4.2 version on the master branch and rebase the rails5 branch.

**Comment by tagliala** [comment]
I'm still locked on 

### Wait for a rack >= 2.0.0 compatible version of Sinatra

please keep using the rails5 branch

**Comment by dreyks** [comment]
@tagliala Sinatra released a 2.0.0.beta2 https://github.com/sinatra/sinatra/releases/tag/v2.0.0.beta2
I understand, that this is just a beta, but just to be sure =)

**Comment by tagliala** [comment]
@dreyks thanks. it should be ok because sinatra is not required for runtime, just for testing

**Comment by eclubb** [comment]
So when can we expect a Rails 5 compatible gem release?

**Comment by edwardmp** [comment]
Thanks for publishing this. Tried It out today but it doesn't seem to work due to the following javascript error:
`rails.validations.js?body=1:188 Uncaught TypeError: Cannot read property 'remove' of undefined`

**Comment by tagliala** [comment]
@edwardmp please start a new issue providing all the information needed and a reduced test case: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue

**Comment by dreyks** [comment]
What's the status on this one?

**Comment by tagliala** [comment]
@dreyks thanks for the ping.

I'm not going to release a gem in a short while, so please keep using the rails5 branch

Also, sinatra is still on beta. If we could drop the sinatra thing and run javascript unit tests against a Node.JS based server (and maybe make that work on Travis), it would be great.

That release should be implemented on the current master branch because it will benefit the Rails 4 version too

**Comment by tagliala** [comment]
Master branch is now compatible with Rails 5.

Expect a new release very soon.

Version will be 6.0.0, I will jump 5.x because now CSV will follow its own versioning for proper SemVer

**Comment by tagliala** [comment]
CSV 6.0.0 released. I'm going for CSV-simple_form

**Comment by dreyks** [comment]
Great news! Highly appreciated, thanks!

**Comment by rubydev** [comment]
@tagliala Hi, could you please update CSV-mongoid for this version (and mongoid 6 and rails 5)?

**Comment by tagliala** [comment]
@rubydev I will give it a try, it is the next on the list!

btw you could give a try to https://github.com/DavyJonesLocker/client_side_validations-mongoid/tree/6-0-dev

**Comment by tagliala** [comment]
@rubydev CSV-Mongoid 7.0.0 released

**Comment by rohaldb** [comment]
"Fetching git://github.com/DavyJonesLocker/client_side_validations.git
fatal: Needed a single revision
Revision rails5 does not exist in the repository
git://github.com/DavyJonesLocker/client_side_validations.git. Maybe you
misspelled it?"
