### ISSUE TITLE
Multi Step Form double click next

### ISSUE THREAD

**Issue by kjakub** [DavyJonesLocker/client_side_validations#647]
I have followed wiki on https://github.com/DavyJonesLocker/client_side_validations/wiki/Validation-in-Multi-Step-Form

It seems alright working, but when validation on certain step fail, i see validation error then if i correct it in input field and directly click on next button again then i have to click 2x to go next step. First click -> only validation message disappear. Checked in console and there is no click event fired it seems...

Also If i click anywhere else in <body> to made validation message disappear first and then next button it works. 

What is going  on?

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)
