### ISSUE TITLE
Security: Uniqueness validator with scope exposes all data

### ISSUE THREAD

**Issue by assimovt** [DavyJonesLocker/client_side_validations#648]
There is an issue I've noticed with the gem, which exposes all data of the associated object when uniqueness validation with scope is used. What's interesting is that uniqueness validator has been disabled via initializer. You can find a sample rails app showing this issue here: https://github.com/assimovt/csv_uniqueness_issue To see it, just start the rails server. Could someone look at it? Thanks!

**Comment by tagliala** [comment]
@assimovt I'm aware of this issue and it is also stated in the readme:

https://github.com/DavyJonesLocker/client_side_validations#security

> Client Side Validations comes with a uniqueness middleware. This can be a potential security issue, so the uniqueness validator is disabled by default. If you want to enable it, set the disabled_validators config variable in config/initializers/client_side_validations.rb:

ClientSideValidations::Config.disabled_validators = []
Note that the FormBuilder will automatically skip building validators that are disabled.

I would like this to bring this feature out of the main gem.

**Comment by assimovt** [comment]
I have it [disabled](https://github.com/assimovt/csv_uniqueness_issue/blob/master/config/initializers/client_side_validations.rb#L4), that's the point that it does not make difference, with it or without, still exposes data.

**Comment by tagliala** [comment]
Sorry, I will take a look asap

**Comment by assimovt** [comment]
:+1:

**Comment by tagliala** [comment]
Just found the source of the issue: https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model.rb#L90

The uniqueness validator passes `{ title: nil }` as `force` parameter in this case, so we must check that if the validator is disabled before the switch statements

Please give a try to the master branch

Thanks for reporting this

**Comment by assimovt** [comment]
@tagliala Awesome, this fixes the issue. How about ```4-2-stable```, is it going to be updated? Or will you publish a new gem with this fix?

**Comment by tagliala** [comment]
@assimovt I'm going to merge 4-2-stable with master, release a new gem and backport this commit to 3-2-stable branch

**Comment by assimovt** [comment]
Thank you!

I've been thinking, what if uniqueness validation is needed, why would this gem expand associated object and dump it's data into the DOM? That's probably another bug and a bigger security flaw?

**Comment by tagliala** [comment]
> why would this gem expand associated object and dump it's data into the DOM? That's probably another bug and a bigger security flaw?

Sorry, I'm not the original author of this gem. I'm aware of security issues (= data disclosure) in that part, but I really want to get rid of that feature

Refers to https://github.com/DavyJonesLocker/client_side_validations/issues/636#issuecomment-146228032
