### ISSUE TITLE
wrong number of arguments (given 1, expected 2..4) - on SELECT fields

### ISSUE THREAD

**Issue by stevenm** [DavyJonesLocker/client_side_validations#649]
After installing Ive had to go over all my forms ( even the ones Im not looking to validate ) and make all my select fields validate: false 

heres the errors ...

wrong number of arguments (given 1, expected 2..4)

Extracted source (around line #71):

        def select_with_client_side_validations(method, choices, options = {}, html_options = {}, &block)
          build_validation_options(method, html_options.merge(name: options[:name]))
          html_options.delete(:validate)
          select_without_client_side_validations(method, choices, options, html_options, &block)

which is being thrown from     <%= f.select(:pipe_id) do %>

  <div class="form-group">
    <%= f.label :pipe_id %><br>
    <%= f.select(:pipe_id) do %>
    <option value="all">All Company Pipes</option>
    <%= options_from_collection_for_select(@pipes, :id, :name , @pipe_metum.pipe_id ) %>
    <% end %>

and is corrected by

  <div class="form-group">
    <%= f.label :pipe_id %><br>
    <%= f.select(:pipe_id, validate: false ) do %>  
    <option value="all">All Company Pipes</option>
    <%= options_from_collection_for_select(@pipes, :id, :name , @pipe_metum.pipe_id ) %>
    <% end %>

**Comment by tagliala** [comment]
Could you please reformat your post with [Markdown](https://guides.github.com/features/mastering-markdown/) and providing a failing test case or a failing application, as well as any information required here: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue?

**Comment by tagliala** [comment]
I'm pretty confident this was solved in 4.2.5

Ref: https://github.com/DavyJonesLocker/client_side_validations/commit/77799b37463d5a42fa17d32aaed50e743ae63d93
