### ISSUE TITLE
client side validations not triggering this validation .

### ISSUE THREAD

**Issue by jayeshdalwadi** [DavyJonesLocker/client_side_validations#650]
This is my model validation but this validation not reflating on UI can someone  help me what wrong for this validation..

validates_exclusion_of :callout_three, in: ->(sitelink) { [sitelink.callout_two, sitelink.callout_one,sitelink.callout_four]}, message: 'should not be the same'

Thanks.

**Comment by tagliala** [comment]
You will probably need a custom client side javascript for doing this

Hope it helps, closing here
