### ISSUE TITLE
BootstrapForm with namespaced model in an engine does not include any validator

### ISSUE THREAD

**Issue by fsauter** [DavyJonesLocker/client_side_validations#651]
Hi together,

I try to use the current master branch of client_side_validations for a [BootstrapForm](https://github.com/bootstrap-ruby/rails-bootstrap-forms) (namespaced model) in an engine. Unfortunately the script block does not contain any validators. Do you have any idea why? It should include at least the presence validator, or not? Is it because the [bootstrap_form/form_helper](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/helper.rb) is not compatible by default with client_side_validations?

**The generated script block:**
````javascript
//<![CDATA[
if(window.ClientSideValidations===undefined)window.ClientSideValidations={};window.ClientSideValidations.disabled_validators=["uniqueness"];window.ClientSideValidations.number_format={"separator":".","delimiter":","};if(window.ClientSideValidations.patterns===undefined)window.ClientSideValidations.patterns = {};window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/;if(window.ClientSideValidations.forms===undefined)window.ClientSideValidations.forms={};window.ClientSideValidations.forms['new_item'] = {"type":"BootstrapForm::FormBuilder","validators":{}};
//]]>
````

**The relevant form parts:**
````ruby
<%= bootstrap_form_for [amos, @item], remote: true, validate: true do |f| %>

# ...
        <div class="col-sm-12">
          <%= f.text_field :number %>
        </div><!-- col-sm-12 -->
# ...
````

**The model (with namespace) validation:**
````ruby
module Amos::Items
  class Item < ActiveRecord::Base
# ....
    validates_presence_of :number
# ...
````

Thanks for any hints and greetings Florian

**Comment by tagliala** [comment]
Hi,

Unfortunately there is no support for `bootstrap_form_for`.

Feel free to develop a plugin like [ClientSideValidations-SimpleForm](https://github.com/DavyJonesLocker/client_side_validations-simple_form) (you can use that repo as a base), I will provie a link in the readme

Hope it helps, closing here
