### ISSUE TITLE
Errors don't show up inline

### ISSUE THREAD

**Issue by mahendhar9** [DavyJonesLocker/client_side_validations#652]
Hello.
Thanks for the awesome gem.
The issue is, I am unable to make the error messages appear inline. I have uncommented the proc in client_side_validations.rb

This is my signup form. What am I doing wrong here :(

````
<div class="container vh-center">
  <div class="form-width">
    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: {id: "signup"},  validate: true) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :email, required: true, autofocus: true, label: "Email", placeholder: "Email"  %>

      <%= f.input :phone_number, required: true, label: false, placeholder: "Phone number" %

      <% if f.object.password_required? %>
      <%= f.input :password, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), label: false, placeholder: "Password" %>
      <%= f.input :password_confirmation, label: false, placeholder: "Password Confirmation" %>
    </div>
    <% end %>

    <div class="form-actions">
      <%= f.button :submit, "Sign up", class: "btn btn-success full-width-btn" %>
    </div>
    <% end %>

    <%= render "devise/shared/links" %>
  </div>
</div>
````

**Comment by tagliala** [comment]
could you please provide a screenshot of what you get and what you want to achieve?

Could you also please provide generated html? You may need extra markup and/or css rules as well as javascript customization to show errors in the way you need

**Comment by factor4** [comment]
Hello! 
I have the same problem! rails 4.2.6, client_side_validations 4.2.3, no devise, no simple_form. The generated markup contain the <script> tag with my model validations, but no error messages show up on filling in the form. I´m using the gem the first time. Should the error messages appear on leaving focus? When I submit the invalid form and it get re-rendered from server-side validations, the error messages show up inline next to the form fields.

@mahendhar9: Did you find a solution?
If not I could provide a sample app...

**Comment by tagliala** [comment]
@factor4 this issue is about the error not appearing inline.

Please make sure you followed instructions, maybe you need to uncomment the initializer: https://github.com/DavyJonesLocker/client_side_validations#initializer

Take a look at this example app: https://github.com/tagliala/test-csv-658/tree/no-simple-form

**Comment by factor4** [comment]
@tagliala Thank you for your response! Yes, in my app errors did not appear inline.
Meanwhile, I have narrowed down my problem. My form is a multistep form which hide/show fieldsets with JS depending on the current step. If I disable the multistep feature and show the whole form, inline errors work as expected! It seems CSV did not recognise the inputs within `$('fieldset').hide()` hidden fieldsets!? Did you have any suggestions to handle this? Thanks a lot!

**Comment by tagliala** [comment]
@factor4 this is covered in our wiki https://github.com/DavyJonesLocker/client_side_validations/wiki/Validation-in-Multi-Step-Form

**Comment by factor4** [comment]
@tagliala Thank you very much! This is exact what I need! 👍

**Comment by tagliala** [comment]
Closing here because lacking of feedbeck

Feel free to provide information and I will reopen
