### ISSUE TITLE
Client side validations custom validator order

### ISSUE THREAD

**Issue by oasisweng** [DavyJonesLocker/client_side_validations#655]
I want to integrate a "zxcvbn" validator to the form.

Along with this validation, I have "presence","length" and "confirmation" validations to my field(in this particular case, my password field).

But, the order of validation goes by "presence", "length", "confirmation", "zxcvbn". However, I want "zxcvbn" to be checked before "confirmation". 

I looked at source code, the order above also matches the order of functions in the `local` object.

Therefore, is there a way to customize the order in which validations are run? What I can think of now is that instead of using object, use array. 

Please tell me how to specify the order of validations! Thank you!

Thank you!

**Comment by tagliala** [comment]
Hi,

this could be an interesting feature. Feel free to submit a PR with proper unit tests

**Comment by tagliala** [comment]
Hi, I think this is already done: by default CSV follows order specified in the model.

Eg:

```rb
class Foo < ApplicationRecord
  validates :email, email: true, presence: true
end
```

![image](https://user-images.githubusercontent.com/556268/66270965-3cb8fb00-e859-11e9-9d54-505ac7545922.png)

```rb
class Foo < ApplicationRecord
  validates :email, presence: true, email: true
end
```
![image](https://user-images.githubusercontent.com/556268/66270973-48a4bd00-e859-11e9-83ab-43aae969e3e2.png)
