### ISSUE TITLE
Uglifier JS Compression causing Syntax Error - Remove double forward slash before CDATA

### ISSUE THREAD

**Issue by patricklindsay** [DavyJonesLocker/client_side_validations#656]
Wasn't sure if this is a Uglifier issue or CSV issue.

I have an issue when running JS compression over pages with the CSV embedded script. 

The compressor seems to be removing the forward slashes before CDATA;

```
# Before
<script>//<![CDATA[ ...
```

```
# After
<script><![CDATA[ ...
```

This is causing:

```
Uncaught SyntaxError: Unexpected token <
```

Any ideas?

Versions:
Uglifier: `3.0.0` (Have tried `2.7.2` also)
client_side_validations (4.2.3)
client_side_validations-simple_form (3.2.3)

**Comment by tagliala** [comment]
Can you configure your compressor to disable inline javascript compression?

**Comment by patricklindsay** [comment]
Yeah I was looking to do that but couldn't find an option in the [uglifier docs](https://github.com/lautis/uglifier#usage)

My compression initializer looks like:

```
Rails.application.configure do
  break unless Rails.env.production?

  # Strip all comments from JavaScript files, even copyright notices.
  uglifier = Uglifier.new output: { comments: :none }

  config.assets.compile = true
  config.assets.debug = false

  config.assets.js_compressor = uglifier
  config.assets.css_compressor = :sass

  config.middleware.use Rack::Deflater
  config.middleware.insert_before ActionDispatch::Static, Rack::Deflater

  config.middleware.use HtmlCompressor::Rack,
    compress_css: false,
    compress_javascript: true,
    enabled: true,
    javascript_compressor: uglifier,
    preserve_line_breaks: false,
    remove_comments: true,
    remove_form_attributes: false,
    remove_http_protocol: false,
    remove_https_protocol: false,
    remove_input_attributes: false,
    remove_intertag_spaces: false,
    remove_javascript_protocol: true,
    remove_link_attributes: false,
    remove_multi_spaces: true,
    remove_quotes: false,
    remove_script_attributes: false,
    remove_style_attributes: false,
    simple_boolean_attributes: false,
    simple_doctype: false
end
```

Setting the HtmlCompressor to not compress Javascript causes all JS not to be compressed rather than just inline JS.

**Comment by tagliala** [comment]
```
# Strip all comments from JavaScript files, even copyright notices.
  uglifier = Uglifier.new output: { comments: :none }
```

could you please try without this one?

**Comment by patricklindsay** [comment]
Removing that line would cause 
```
 config.assets.js_compressor = uglifier
```

&

```
 javascript_compressor: uglifier,
```
To throw an undefined error. If I remove all lines then the JS is not compressed.

**Comment by tagliala** [comment]
I mean, from `uglifier = Uglifier.new output: { comments: :none }` to `uglifier = Uglifier.new`

**Comment by tagliala** [comment]
I'm pretty confident that the problem is in the `HtmlCompressor`, which should be responsible of compressing inline javascript. I would change `compress_javascript: true` to `false`

**Comment by patricklindsay** [comment]
Yeah that seemed to do the trick, I'm sure I had tried that and it stopped compressing all JS instead of just inline.. oh well. 

I'm closing this. There is still a problem that Uglifier is stripping the double forward slash before CDATA but I don't think this is a CSV issue.

Thanks for your help @tagliala

**Comment by tagliala** [comment]
IMHO the error should be reported to HtmlCompressor because it treats //<![CDATA[` as a standard comment and t herefore strips it

**Comment by tagliala** [comment]
@patricklindsay 

btw I'm not getting this error.

Config:

```rb
    uglifier = Uglifier.new output: { comments: :none }
    config.middleware.use HtmlCompressor::Rack,
        compress_css: false,
        compress_javascript: true,
        enabled: true,
        javascript_compressor: uglifier,
        preserve_line_breaks: false,
        remove_comments: true,
        remove_form_attributes: false,
        remove_http_protocol: false,
        remove_https_protocol: false,
        remove_input_attributes: false,
        remove_intertag_spaces: false,
        remove_javascript_protocol: true,
        remove_link_attributes: false,
        remove_multi_spaces: true,
        remove_quotes: false,
        remove_script_attributes: false,
        remove_style_attributes: false,
        simple_boolean_attributes: false,
        simple_doctype: false
```

output:
```js
/*<![CDATA[*/void 0===window.ClientSideValidations&&(window.ClientSideValidations={}),window.ClientSideValidations.disabled_validators=["uniqueness"],window.ClientSideValidations.number_format={separator:".",delimiter:","},void 0===window.ClientSideValidations.patterns&&(window.ClientSideValidations.patterns={}),window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/,void 0===window.ClientSideValidations.forms&&(window.ClientSideValidations.forms={}),window.ClientSideValidations.forms.new_post={type:"SimpleForm::FormBuilder",error_class:"error",error_tag:"small",wrapper_error_class:"error",wrapper_tag:"div",wrapper_class:"input",wrapper:"vertical_form",validators:{"post[email]":{format:[{message:"is invalid","with":{source:"^[^@\\s]+@([^@\\s]+\\.)+[^@\\W]+$",options:"g"}}]}}};/*]]>*/
```

Rails 4.2.6, CSV @ master, htmlcompressor (0.3.0), uglifier (3.0.0)

**Comment by tagliala** [comment]
please also give a try at the `master` branch, because I'm now using `javascript_tag` instead of `content_tag` which provides better CDATA comments

**Comment by patricklindsay** [comment]
It's now compressing without any issues. Can't pin point the fix though as I haven't been able to reproduce the original issue.
