### ISSUE TITLE
validation: false will not turn off boolean field validation!

### ISSUE THREAD

**Issue by oasisweng** [DavyJonesLocker/client_side_validations#658]
I am using Simple Form for a Staff form that starts as this

```
<%= simple_form_for(@staff,  as: :staff,
                             url: staffs_path, 
                             method: "post",
                             html:   { multipart: true, 
                                       class: 'form-horizontal'},
                             validate: true,
                             wrapper:  :horizontal_form) do |f| %>
```

Then, I have a `is_intern` boolean field whose validation I want to disable. It is the following code:

```
<%= f.input :is_intern, as: :boolean, wrapper: :horizontal_boolean, label: "Tick for Internship", validate: false %>
```

But the validation will still go off. 

I did set up some hooks in my JS file to show some customized messages:

```
 window.ClientSideValidations.callbacks.element.pass = function(element, callback){
  }
  window.ClientSideValidations.callbacks.element.fail = function(element, message, callback) {
  }
```

However, `fail` hook never gets called for `is_intern` boolean field, and pass calls everytime I click on it.

How to fix?

**Comment by tagliala** [comment]
Sorry, unable to reproduce.

https://github.com/tagliala/test-csv-658

Relevant  commits: https://github.com/tagliala/test-csv-658/commit/92491eaffbcf62ef8aad6321bd1dae44d38afa71 https://github.com/tagliala/test-csv-658/commit/87f7594f56da14a5be47df5e6c9126a5d0086092

Please provide a reduced test case: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue
