### ISSUE TITLE
Manually validate the complete form

### ISSUE THREAD

**Issue by ChakreshwarSharma-BTC** [DavyJonesLocker/client_side_validations#660]
How to validate the form before form.submit().

I want to achive like $("#my_form").validate(). If the form contains error, then they must be displayed.

**Comment by tagliala** [comment]
> How to validate the form before form.submit().

This should be done automatically and you could use `ClientSideValidations.callbacks.form.fail(form, eventData)` callback

Ref: https://github.com/DavyJonesLocker/client_side_validations#callbacks

**Comment by santosh-btc** [comment]
@tagliala Please Provide proper Documentation For `ClientSideValidations.callbacks`. i fail to use above code.

**Comment by tagliala** [comment]
please provide me an application with the minimum amount of code and gems with your failing code or a failing test case

**Comment by santosh-btc** [comment]
@tagliala : in our application we have a button which checks that whether the form is valid or not, we didn't submit the form anywhere , so is it possible to achieve it by using this gem ,  It would be helpful for us if you provide some example code.

Thanks

**Comment by tagliala** [comment]
Ok, got it.

You don't need callbacks to achieve this.

It is explained here for `input` tags: https://github.com/DavyJonesLocker/client_side_validations/wiki/Manually-trigger-input-validation but it cab be applied to the whole form too:

erb:
```erb
<!-- ... -->
    <%= f.button 'Check Form', type: 'button', id: 'check-form-j' %>
<!-- ... -->
```

coffee:
```coffee
$(document).on 'click', '#check-form-j', ->
  $form = $(this).closest('form')
  $form.isValid($form[0].ClientSideValidations.settings.validators)
```

Closing here, hope it helps

**Comment by santosh-btc** [comment]
$form.isValid($form[0].ClientSideValidations.settings.validators  is always return true in my case but by form is not validate.

**Comment by tagliala** [comment]
Sorry, @santosh-btc. I can't understand what you are trying to achieve.

The above snippet runs validations on the form.

If the form is not valid, you will see the errors on the fields. Then CSV will trigger the `form:validate:fail.ClientSideValidations` event, so you can listen for it with:

```coffee
$(document).on 'form:validate:fail.ClientSideValidations', ->
  console.log 'validations failed'
```

please notice that this will catch events for every form, so you should delegate to your form's selector ID if needed

**Comment by tagliala** [comment]
Also, I'm properly getting `true` and `false` in my use case.

![image](https://cloud.githubusercontent.com/assets/556268/16194026/b48ebd70-36f2-11e6-9dab-1c4d3d03ac9b.png)

![image](https://cloud.githubusercontent.com/assets/556268/16194039/c6b02bc4-36f2-11e6-9c0a-d399e7b2231e.png)

application.js:
```js
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file. JavaScript code in this file should be added after the last require_* statement.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require rails.validations
//= require_tree .
```

coffee:
```coffee
$(document).on 'click', '#check-form-j', ->
  $form = $(this).closest('form')
  alert $form.isValid($form[0].ClientSideValidations.settings.validators)
```

erb:
```
<%= form_for(user, validate: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <%= f.button 'Check Form', type: 'button', id: 'check-form-j' %>
  </div>
<% end %>

```

**Comment by santosh-btc** [comment]
@tagliala Thanks for reply.
Now i am adding a select box to form dynamically which is not a form attribute.so how to validate it?

**Comment by tagliala** [comment]
@santosh-btc you're welcome

sorry but this is not a support forum, we should track issues with the library.

Dynamic fields: https://github.com/DavyJonesLocker/client_side_validations/wiki/Validating-dynamically-added-forms
