### ISSUE TITLE
wrong number of arguments (4 for 5)

### ISSUE THREAD

**Issue by arvindvyas** [DavyJonesLocker/client_side_validations#663]
I follow the steps with this http://railscasts.com/episodes/263-client-side-validations and install it in my spree application

**Comment by tagliala** [comment]
Sorry, Ryan's railscast is a little bit outdated.

If I'm right, Spree is based on 4.2.6 and I can confirm that Rails 4.2.6 is fully supported by CSV 4.2.4

Please follow our Readme to install and configure CSV on Rails 4.2.6

Hope it helps, closing here
