### ISSUE TITLE
Rails 5 JavaScript error on Format validation

### ISSUE THREAD

**Issue by glennfu** [DavyJonesLocker/client_side_validations#670]
Devise appears to add this to my model:

```
email_regexp = /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/
validates_presence_of   :email, if: :email_required?
validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
validates_format_of     :email, with: email_regexp, allow_blank: true, if: :email_changed?
```

In the JavaScript `format` method of CSV I see:
```
if (options["with"] && !options["with"].test(element.val())) {
```

This line errors with "TypeError: options.with.test is not a function"

The value of `options["with"]` is `{ source="^[^@\s]+@([^@\s]+\.)+[^@\W]+$",  options="g"}`

The CSV tests suggest it expects `options["with"]` to be a String, but clearly it's not the case here!

Injected at the end of the form is:
```
if(window.ClientSideValidations===undefined)window.ClientSideValidations={};window.ClientSideValidations.disabled_validators=["uniqueness"];window.ClientSideValidations.number_format={"separator":".","delimiter":","};if(window.ClientSideValidations.patterns===undefined)window.ClientSideValidations.patterns = {};window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/;if(window.ClientSideValidations.forms===undefined)window.ClientSideValidations.forms={};window.ClientSideValidations.forms['new_user'] = {"type":"ActionView::Helpers::FormBuilder","input_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003cspan id=\"input_tag\" /\u003e\u003clabel for=\"\" class=\"message\"\u003e\u003c/label\u003e\u003c/div\u003e","label_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003clabel id=\"label_tag\" /\u003e\u003c/div\u003e","validators":{"user[email]":{"format":[{"message":"is invalid","with":{"source":"^[^@\\s]+@([^@\\s]+\\.)+[^@\\W]+$","options":"g"},"allow_blank":true}]},"user[password]":{"length":[{"messages":{"minimum":"is too short (minimum is 8 characters)","maximum":"is too long (maximum is 72 characters)"},"allow_blank":true,"minimum":8,"maximum":72}]}}};
```

**Comment by tagliala** [comment]
> The CSV tests suggest it expects options["with"]

Nope, it should be a Regular Expression: https://github.com/DavyJonesLocker/client_side_validations/blob/master/coffeescript/rails.validations.coffee#L231

```coffee
return options.message if options.with and !new RegExp(options.with.source, options.with.options).test(element.val())
```

Could you please provide which version of Rails and CSV are you using?

**Comment by glennfu** [comment]
Rails v 5.0.0, and installed CSV via: `gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: "rails5"` which put `revision: 968e614c6a79fcd8ea55dad4aca3c4175e415870` in my Gemfile.lock

**Comment by tagliala** [comment]
@glennfu 

```
if (options["with"] && !options["with"].test(element.val())) {
```

where does this snippet of code come from?

**Comment by glennfu** [comment]
I just realized I had run `rails g client_side_validations:copy_assets` on a different version of CSV, before updating to the "rails5" branch, so I was actually running the old code because of that. Deleting that generated file now properly loads the right code. Sorry about that!

**Comment by tagliala** [comment]
don't worry

glad you solved!

If you want to add a heads  to the readme, feel free to submit a PR (against the master branch) or suggest a sentence I could add to https://github.com/DavyJonesLocker/client_side_validations#install

**Comment by glennfu** [comment]
PR submitted: #671
