### ISSUE TITLE
Email uniqueness does not work in client side

### ISSUE THREAD

**Issue by leongg** [DavyJonesLocker/client_side_validations#676]
Hi, my email client side uniqueness validator does not work in client side.

My  code is: 
`validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_uniqueness_of :email`

and my form:

> <%= simple_form_for resource, as: resource_name, url: registration_path(resource_name), validate: true do |f| %>
>               <div class="form-group">
>                 <%= f.text_field :name, autofocus: false, placeholder: "Nombre", class: 'form-control'%>
>               </div>
> 
>               <div class="form-group">
>                 <%= f.email_field :email, validate: { uniqueness: true }, autofocus: false, placeholder: "Email", class: 'form-control' %>
>               </div>
>               <span class="help-block"></span>
> 
>               <div class="form-group">
>                 <%= f.password_field :password, autocomplete: "off", placeholder: "Clave", class: 'form-control'  %>
>               </div>
>               <%= f.submit t('activerecord.button.models.application_form.sign_up'), class: 'btn btn-lg btn-primary btn-block' %>
>             <% end %>

It's working the name, password, email (format) but not the email uniqueness. 

How can I fix it?

Thanks!

**Comment by tagliala** [comment]
> but not the email uniqueness.

This require that you enable a remote validator which is disabled by default because it could cause Information Disclosure. Use it ar your own risk:

https://github.com/DavyJonesLocker/client_side_validations#security

Hope it helps

**Comment by leongg** [comment]
Thanks @tagliala !

Got the last question, why is it a bad idea to perform a real time email uniqueness validation? 

the thing is that I have a form that people answer and in same form, people register their account. 

Thanks again!

**Comment by tagliala** [comment]
Basing on how is the validator implemented, it could bring to information disclosure via brute force (e.g: reconstruct the phone number of the user).

Maybe there is a better way of implementing this, but I'm not into security and I'm opened to PR in #612
