### ISSUE TITLE
Validation error message is not generating on turbolinks:load

### ISSUE THREAD

**Issue by JosephA91** [DavyJonesLocker/client_side_validations#677]
Validation error message is not generating on turbolinks:load but generates when the page is refreshed. 

Rails Version: Version 4.2.6
Client_Side_Validation: Version 4.2.7
### Model:

```
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :post
  belongs_to :user
end
```
### Form:

```
<%= form_for [@post, @post.comments.build], validate: true do |f| %>

  <div class="input-group">
    <%= f.text_field :content, class: "form-control", autocomplete: :off %>
    <span class="input-group-btn">
      <%= f.submit "Send", class: "btn btn-primary pull-right" %>
    </span>
  </div>

<% end %>
```
### Generated HTML:

```
<form data-validate="true" novalidate="novalidate" class="new_comment" id="new_comment" action="/posts/21/comments" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="ZmpADuX73JqNvAh5wljYCmk68wXioVLFP1YDHY+71l4YADgQglKiQAODBrc5OrXvioqurjI5/JwqfO2qJXPPvg==" />

  <div class="input-group">
    <input class="form-control" autocomplete="off" type="text" name="comment[content]" id="comment_content" />
    <span class="input-group-btn">
      <input type="submit" name="commit" value="Send" class="btn btn-primary pull-right" />
    </span>
  </div>
</form>

<script>
//<![CDATA[
if(window.ClientSideValidations===undefined)window.ClientSideValidations={};window.ClientSideValidations.disabled_validators=["uniqueness"];window.ClientSideValidations.number_format={"separator":".","delimiter":","};if(window.ClientSideValidations.patterns===undefined)window.ClientSideValidations.patterns = {};window.ClientSideValidations.patterns.numericality=/^(-|\+)?(?:\d+|\d{1,3}(?:\,\d{3})+)(?:\.\d*)?$/;if(window.ClientSideValidations.forms===undefined)window.ClientSideValidations.forms={};window.ClientSideValidations.forms['new_comment'] = {"type":"ActionView::Helpers::FormBuilder","input_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003cspan id=\"input_tag\" /\u003e\u003clabel for=\"\" class=\"message\"\u003e\u003c/label\u003e\u003c/div\u003e","label_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003clabel id=\"label_tag\" /\u003e\u003c/div\u003e","validators":{"comment[content]":{"presence":[{"message":"can't be blank"}]}}};
//]]>
</script>
```
### Issue:

The generated input HTML should look like this:
`<input class="form-control" autocomplete="off" type="text" name="comment[content]" id="comment_content" data-validate="true" />`

`data-validate="true"` is not generating on turblinks:load but generates ok when the page is refreshed.

**Comment by tagliala** [comment]
Could you please share on github a sample application showing the issue?

**Comment by JosephA91** [comment]
Hi @tagliala, thank you for your reply and work on the Client_side_validations gem.

I am unfortunately unable to provide the source code for the application as it belongs to an organisation. The example above is about the extent of what I can release.

If you need any clarification of the above code, please let me know.

I am just looking for any general tips you may have on this?

Thank you for your help.

**Comment by tagliala** [comment]
> I am unfortunately unable to provide the source code for the application as it belongs to an organisation. The example above is about the extent of what I can release.

You could start a new rails application with just the code and steps needed to reproduce the bug

**Comment by JosephA91** [comment]
Hi @tagliala, the application I am working on is quite large and has a number of nested resources, so it would be difficult to replicate without reproducing the current source code. 

What I have discovered is that client_side_validations in my form as shown above, loads correctly on page load but when using turbolinks:load the javascript fails to load on the client.

I am wondering if you have come across this or have any idea why this might occur? Or if you could point me in the right direction?

Thank you for your help.

**Comment by tagliala** [comment]
> Hi @tagliala, the application I am working on is quite large and has a number of nested resources, so it would be difficult to replicate without reproducing the current source code.

You should extract the minimum amount of resources to reproduce the issue and lock gems to the same versions you are using.

> I am wondering if you have come across this or have any idea why this might occur? Or if you could point me in the right direction?

CSV has one single file, you can copy the .coffee file in your application and debug it

**Comment by JosephA91** [comment]
See below.

Kind regards,

Joseph Amato
Co-founder, director

Indionic

_____________________________

**Comment by tagliala** [comment]
No feedback, closing here
