### ISSUE TITLE
jQuery-Tags-Input validation failed 

### ISSUE THREAD

**Issue by viveksingh1115** [DavyJonesLocker/client_side_validations#678]
Hi,
I used following gems
gem 'simple_form', '~> 3.3', '>= 3.3.1'
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations', branch: 'rails5'
gem 'client_side_validations-simple_form', github: 'DavyJonesLocker/client_side_validations-simple_form', branch: 'rails5'

and For tags input I used library called jQuery-Tags-Input https://github.com/xoxco/jQuery-Tags-Input

The required validation does not work.
<%= f.input :tags, label: 'Input Tags', input_html: { id: 'tags'} %>

In model 
validates :tags, presence: true

Please suggest how I validate this.
Thanks,
![screen shot 2016-10-13 at 11 46 37 am](https://cloud.githubusercontent.com/assets/13467710/19338446/c20cc788-913a-11e6-87ba-13cf71ad1b9e.png)

**Comment by tagliala** [comment]
You probably need to trigger an event on the input field hidden by this plugin, take a look here: https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins

**Comment by tagliala** [comment]
Hope it helps
