### ISSUE TITLE
Error labels is not appended to an Input with Autofocus and Turbolinks.

### ISSUE THREAD

**Issue by eozelius** [DavyJonesLocker/client_side_validations#681]
Hello, I hope you are all well.

I am having an bizarre issue with turbolinks, client_side_validations and the Autofocus property.  When I use both libraries, and the autofocus property on a text input, the first time the page loads, (from a turbolinks link) the error message is not being appended to the input.  If you refresh the page, the message will properly be appended to the input.

`<%= f.text_field :name, class: 'form-control', autofocus: true %>`

when I add the autofocus property, the message is not being appended to the input, the input is wrapped in the `<div class="field-with-errors>`, but the label is not appended to the input.  If you try to submit the form, it will not submit until you have passed the validation

The rest of the inputs are working well.

Here is the weird part, this issue resolves itself if you refresh the page.  I have had a handful of weird issues with turbolinks, and overlapping JS/CSS, but this one has be stumped.

turbolinks version: 5.0.1
client_side_validation version: 4.2.7
rails version: 4.2.7.1
ruby version: 2.3.1p112
Occurs in all browsers on all OS's

Issue can be observed at rndev.mcfinternal.com, 
1. select any of the Notes
2. you will be forwarded to a form, the validations don't work for the Recipient Name field (autofocus is enabled), but they work for the rest of the fields.
3. Refresh the page, the validations will now work for Recipient Name

**Comment by tagliala** [comment]
It seems to work for me

![image](https://cloud.githubusercontent.com/assets/556268/20148899/04e7d53c-a6af-11e6-8028-c23a0aef7e91.png)

**Comment by eozelius** [comment]
Hello @tagliala, you are correct it was working for you.  I forgot to push a commit.

The issue is visible now.

**Comment by tagliala** [comment]
Sorry, cannot confirm.

Gemfile
```rb
gem 'client_side_validations'
gem 'rails', '4.2.7.1'
gem 'turbolinks'
```

Gemfile.lock
```
    rails (4.2.7.1)
      actionmailer (= 4.2.7.1)
      actionpack (= 4.2.7.1)
      actionview (= 4.2.7.1)
      activejob (= 4.2.7.1)
      activemodel (= 4.2.7.1)
      activerecord (= 4.2.7.1)
      activesupport (= 4.2.7.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.7.1)
      sprockets-rails
    client_side_validations (4.2.7)
      jquery-rails (>= 3.1.2, < 5.0.0)
      js_regex (~> 1.0, >= 1.0.9)
      rails (>= 4.0.0, < 4.3.0)
    turbolinks (5.0.1)
      turbolinks-source (~> 5)
```

routes
```rb
  get :turbolinks, to: 'posts#turbolinks'
  resources :posts, only: [:new, :create]
```

Model
```rb
class Post < ActiveRecord::Base
  validates :email, presence: true
end
```

application.js
```js
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require rails.validations
//= require_tree .
```

/app/views/posts/turbolinks.html.erb
```rb
<%= link_to 'New Post', new_post_path %>
```

/app/views/posts/new.html.erb
```rb
<%= form_for @post, validate: true do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, autofocus: true %>

  <%= f.submit %>
<% end %>
```

1. Open `localhost:3000/turbolinks`
![image](https://cloud.githubusercontent.com/assets/556268/20181633/3dffacb8-a75f-11e6-972c-2496fc50bfb1.png)

2. Click on `New Post`, making sure it performs an xhr request
![image](https://cloud.githubusercontent.com/assets/556268/20181700/76cb22ca-a75f-11e6-816f-222eb6111077.png)

3. Check that autofocus is working
![image](https://cloud.githubusercontent.com/assets/556268/20181717/8afeeeac-a75f-11e6-9504-8dec9334eeb4.png)

4. Blur field (I've used tab) and make sure CSV adds an error
![image](https://cloud.githubusercontent.com/assets/556268/20181739/a18f9036-a75f-11e6-8d98-f215219203fc.png)

**Comment by eozelius** [comment]
hello @tagliala,  thanks for taking the time to look at this.

If you add a couple inputs and an autofocus property to the form, you might be able to see the issue.  Try adding this form:

```
<%= form_for @post, validate: true do |f| %>
  <%= label_tag :title%>
  <%= text_field_tag :title %>

  <%= f.label :email %>
  <%= f.email_field :email, autofocus: true %>
  
  <%= label_tag :first_name %>
  <%= text_field_tag :first_name %>

  <%= label_tag :last_name %>
  <%= text_field_tag :last_name %>

  <%= f.submit %>
<% end %>
```

**Comment by tagliala** [comment]
Still can't confirm.


```erb
<%= form_for @post, validate: true do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :minimum_players, autofocus: true %>
  <%= f.email_field :minimum_players %>

  <%= f.label :maximum_players %>
  <%= f.email_field :maximum_players %>

  <%= f.label :players %>
  <%= f.email_field :players %>

  <%= f.submit %>
<% end %>
```

![image](https://cloud.githubusercontent.com/assets/556268/20183844/025e24c0-a767-11e6-82f7-fb06e948a034.png)

**Comment by eozelius** [comment]
Hello @tagliala,

The issue is not that autofocus is not working.  The issue is that the validations are not working on the input with the auto-focus, to see the issue you will need to write some basic validations, and then the field with the auto-focus will not work with client_side_validations.

Model

```
class Post < ActiveRecord::Base
  validates :email, presence: true
  validates :minimum_players, presence: true
  validates :maximum_players , presence: true
  validates :players, presense:true
end
```

Then use the same form, the client_side_validations will work for :email, :maximum, and :players, but the validations will not work for :minimum.

I hope that helps, thanks again.

**Comment by tagliala** [comment]
@eozelius as you can see in my above screenshot, `minimum` has a thick red border which means that validations ran on that field

**Comment by eozelius** [comment]
Ok, @tagliala  thanks for taking a look at this.  I will let you know if I am able to solve my issue.

Regards.

**Comment by tagliala** [comment]
@eozelius You're welcome. Please let me know if you are able to identify the bug or if I've missed something

**Comment by eozelius** [comment]
I have found source of the issue, for some reason (still working on it) a rich text editor we are using is causing this behavior.

No issue with turbolinks or client_side_validations.

**Comment by tagliala** [comment]
Thanks, please share the name of the gem if you can

**Comment by eozelius** [comment]
the gem/editor (in combination with my own code) that was causing the issue is WYSIhtml5 editor, 
`gem 'bootstrap-wysihtml5-rails'`

When the editor is initialized, the textarea is focused, so the autofocused field loses focus, and an error-message is attached to the input, because it lost focus and is blank.  To fix that issue, I wrote a callback to remove the error label when the editor had finished loading.  I'm still not sure why the validations didn't start working after the trading focus, and removing labels.  But It is working now.
