### ISSUE TITLE
format validation with regex containing a dollar sign generates invalid regex

### ISSUE THREAD

**Issue by tomca32** [DavyJonesLocker/client_side_validations#684]
We validate format with the following regex:
```ruby
/\A\$?[\d^0](\d{0,2})(,?\d{3})+\Z/
```

In the frontend this gets converted into the following string:
```javascript
^?[\d^0](\d{0,2})(,?\d{3})+(?=\n?$)
```

which is invalid regex and raises the following error:
```
Uncaught SyntaxError: Invalid regular expression: /^?[\d^0](\d{0,2})(,?\d{3})+(?=\n?$)/: Nothing to repeat
```

This is due to the following bug in JSRegex dependency: https://github.com/janosch-x/js_regex/issues/2

**Comment by tagliala** [comment]
Yes, there is a high chance that the bug is due to js_regex because we are completely relying on that gem to create regexp

https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/core_ext/regexp.rb#L5

**Comment by tomca32** [comment]
JSRegex released a new version 1.0.19 where this is fixed. It would be great if client_side_validations could pull up a new version.

**Comment by tomca32** [comment]
Oh, it already does. Cool. Seems like everything's good now.

**Comment by tomca32** [comment]
Maybe it wouldn't be a bad idea to raise the dependency requirement to:

```ruby
spec.add_dependency 'js_regex', '~> 1.0', '>= 1.0.19'
```

since this seems to be a pretty serious bug.

**Comment by tagliala** [comment]
Will do that

**Comment by tagliala** [comment]
Version 4.2.10 released, thanks
