### ISSUE TITLE
Have to click submit button twice to submit form.

### ISSUE THREAD

**Issue by anthony-robin** [DavyJonesLocker/client_side_validations#691]
_This issue was not originally created by me but as the contributor closed it, I created a new one with same content as @marnold1 wrote first. ([original issue](https://github.com/DavyJonesLocker/client_side_validations/issues/469))_

Occurs under this scenario.

1. Submit a form with validation errors.
2. Correct all the errors but dont tab out of the last item fixed. So the error message remains.
3. Click down on the submit button (validation occurs on mousedown removing error messages so form and button shifts upwards). On mouseup the submit button has moved so no longer triggers the submission.
4 Now there are no error messages the submit button can be selected again to submit the form.
Is it possible to change the triggering events so it validates on mouseup? I see this error on the contact form for http://zinergia.co/.

Note: I know this would work if all error messages were inline but that does not work for our design.

**Comment by tagliala** [comment]
Hi,

sorry but a copy & paste is not enough. Also, zinergia.co is dead for me.

Closing here until this issue meets [Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md)
