### ISSUE TITLE
Rails 5.1 compatibility

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#696]

**Comment by tagliala** [comment]
At the moment it works out of the box. I will not support `form_with` because it is softly deprecated and will stay there until Rails 6. 

Please use `rails51` branch if you need Rails 5.1 compatibility. I will merge changes into master asap Rails 5.1 will be released

**Comment by tagliala** [comment]
Merged on the master branch

**Comment by klamath** [comment]
@tagliala Hi! Can you please provide proof links for deprecation of `form_with`?
I thought that `form_for` & 'form_tag` is softly deprecated. Now I'm totally confused (

**Comment by tagliala** [comment]
@klamath sorry

Fixed my comment above:

> I will not support `form_with` because *`form_for` and `form_tag` are softly deprecated and will stay there until Rails 6. *

**Comment by murdoch** [comment]
Would it be hard to support `form_with`? I reckon a lot of people will like it :) Maybe I'll try and do it myself.

**Comment by tagliala** [comment]
@murdoch yes, please.

IIRC, I've skipped `form_with` because its implementation was not straightforward

A PR and a test case would be highly appreciated

**Comment by reckerswartz** [comment]
@tagliala does it still not support form_with?

**Comment by tagliala** [comment]
@reckerswartz I don't know if you are still interested, but I've added `form_with` support to the master branch. I will release a new version of the gem in a few days
