### ISSUE TITLE
Bundler could not find compatible versions for gem "client_side_validations"

### ISSUE THREAD

**Issue by alon8900** [DavyJonesLocker/client_side_validations#698]
Hi,
I've removed the `branch: rails5` at the gemfile, and I've got this Error:
```
Bundler could not find compatible versions for gem "client_side_validations":
  In Gemfile:
    client_side_validations
```

**Comment by tagliala** [comment]
@alon8900 please post the relevant lines in your gemfile

**Comment by rohaldb** [comment]
@alon8900 you need to upgrade to the newest version of rails (or downgrade). The gem is not supported on rails 5.0.

**Comment by tagliala** [comment]
> The gem is not supported on rails 5.0.

CSV does support Rails 5.0 and 5.1.0.rc1 :)

**Comment by rohaldb** [comment]
Yep I was running 5.0.0 @tagliala, and I assumed so was @alon8900

**Comment by tagliala** [comment]
Closing here
