### ISSUE TITLE
Error messages not displaying

### ISSUE THREAD

**Issue by rohaldb** [DavyJonesLocker/client_side_validations#699]
After following the installation guide, I can't get the text for the error messages to display. I built a form using form_for, with an input field for an attribute :name, with the validation `validates_presence_of :name`
When i don't enter anything in the field and tab to the next line, an html element 
`<div class="field_with_errors">` is generated but there is no text describing the error. The input field is also pushed to a new line. 

On page load:
<img width="973" alt="screen shot 2017-04-04 at 3 22 31 pm" src="https://cloud.githubusercontent.com/assets/12228952/24642450/c4eea852-194a-11e7-8446-0f2b9742283b.png">
After tabbing:
<img width="1116" alt="screen shot 2017-04-04 at 3 25 03 pm" src="https://cloud.githubusercontent.com/assets/12228952/24642481/ecc8420c-194a-11e7-86a5-3479fe575844.png">

What is causing this?

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

Unfortunately, I cannot keep this open.

Please take another look at our contributing guidelines: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue

Feel free to edit the first post providing all the information needed and ping me, I will consider reopening.
