### ISSUE TITLE
Validation for price range doesn't work correctly

### ISSUE THREAD

**Issue by Rubioli** [DavyJonesLocker/client_side_validations#704]
Great `gem` 👍 

In my application I want to `validate` the `price` and it can't be *less then* $`0.010`.

*I added this to my Model:*
```
class Product < ActiveRecord::Base
  validates :price, inclusion: {in: 100..0.010, message: "Can't be less then $0.010"}
```

*And my form:*
```
= simple_form_for @product, validate: true do |f|
    = f.input :price, input_html: { value: '10', type: 'number' }
```

Currently whatever I write, I get `Can't be less then $0.010`. I have tested with *$10*, *$0.010* & *0.009* and all of them gets the same message.

What have I done wrong?

Any help is appreciated and thanks in advanced!

**Comment by tagliala** [comment]
Hi,

this should be work, but apparently CSV doesn't convert numeric ranges before checking boundaries.

At the moment, you could use

```
  validates :price, numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 0.010 }
```

but this should be fixed

**Comment by tagliala** [comment]
Nope, it works.

Please fix the range, it is supposed to be in ascending order, so [0.01..100] but I would avoid mixing floats and integers. I would go for the numericality validator

Hope it helps
