### ISSUE TITLE
Validate file information on client side

### ISSUE THREAD

**Issue by bbReddera** [DavyJonesLocker/client_side_validations#707]
I am using client_side_validations along with MongoDb, Simple form and mongoid-paperclip, all the validations are showing proper error messages, one beard thing is, if there are validation failure for any file or non-file field the attached files disappears and the user is required to attach the file again and need to submit the form again. 

Earlier, I thought there is some issue with my code, but then I created a whole new sample app to test this out and the same problem occurs there.

I am attaching the whole sample running app in the zip format. You just need to add a user with wrong image extension or of wrong image size and  it will display
[mongo-simple-client_side.zip](https://github.com/DavyJonesLocker/client_side_validations/files/1090558/mongo-simple-client_side.zip)
 the error message, but it will reset the image you attached.

Thanks, for any help in advance.

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

> if there are validation failure for any file or non-file field the attached files disappears

You mean a client side validation failure?

Could you please also try the behaviour without client side validations?

> You just need to add a user with wrong image extension or of wrong image size and it will display
mongo-simple-client_side.zip

Could you please upload the example application to a repository on github?

I do not feel confident in downloading zip blobs, I would like to remove the attachment

**Comment by bbReddera** [comment]
Hello,

Here is the github link for the sample app: 

https://github.com/chiragagrawal/mongo_client_side_validation_issue.

Also, it is like when I am adding a wrong image(either of wrong content type or wrong dimensions) for the user model, it is running the validation which are in my model **User.rb** and it is showing the errors also but it is resetting the attached, which means user need to again attach the image or file.

**Comment by tagliala** [comment]
I'm seeing that you are using an old and unsupported version of CSV

By the way, could you please try without client side validations and let me know the results?

**Comment by bbReddera** [comment]
I tested it without client side validations and it seems Paperclip won't store the path and it resets the form, but the issue here is "**client side validations**" for attachment is not performed at client side, it is submitting the request into the backend and there it is checking for the image size, dimensions and presence.

**Comment by tagliala** [comment]
Ok, thanks.

Sorry but this feature is not supported and it should also be hard to implement

I think the implementation should rely on [FileReader API](https://developer.mozilla.org/it/docs/Web/API/FileReader) and [Blob API](https://developer.mozilla.org/en-US/docs/Web/API/Blob) (IE10+), with some [complex header inspection methods](https://stackoverflow.com/a/29672957/1675923) and maybe more stuff

Please note that you could restrict file extension by adding `accept: 'image/png,image/gif,image/jpeg'` to your [`file_field` tag](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-file_field) (but this is not going to test the actual mime type of the file, you can rename an exectuable to `.jpg` and upload it)

Hope it helps, closing here
