### ISSUE TITLE
Using Proc outside of if condition

### ISSUE THREAD

**Issue by jfyzhao** [DavyJonesLocker/client_side_validations#713]
Is this supported? Validation seems to work correctly but not trigger the client side validation. Gives an error when I try to force it by setting validate: true on the individual input.

Using v9.3

For example:
`validates :price, numericality: { greater_than: Proc.new { |offer| offer.parent_model.some_attribute }, less_than: 1000 }
`

**Comment by tagliala** [comment]
Hi,

this use case should work.

As per [Readme](https://github.com/DavyJonesLocker/client_side_validations#conditional-validators)

> By default conditional validators are not evaluated and passed to the client. We do this because the state model when the form is rendered is not necessarily the state of the model when the validations fire server-side. However, if you wish to override this behavior you can do so in the form. 

Please use

```erb
<%= f.text_field :price, validate: true %>
```

in your template

Hope it helps
