### ISSUE TITLE
Rails 5.04 javascript working but just adding empty line

### ISSUE THREAD

**Issue by dokuzbir** [DavyJonesLocker/client_side_validations#714]
I am using turbolinks and  rails 5.04 on page javascript working. But just adding empty line not showing error. What can cause that error? **version is 9.3.4**

**My model**
```
class User < ApplicationRecord
  has_many :reviews
  has_many :user_provider, :dependent => :destroy
  has_many :bookings
  has_many :devices
  has_many :notifications, foreign_key: :recipient_id
  after_create :send_wellcome_mail
  after_create :create_device
    validates :phone, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true
end
```

**On html javascript working in form** 

"`<form class="new_user" id="new_user" novalidate="novalidate" data-client-side-validations="{"html_settings":{"type":"ActionView::Helpers::FormBuilder","input_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003cspan id=\"input_tag\" /\u003e\u003c/div\u003e","label_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003clabel id=\"label_tag\" /\u003e\u003c/div\u003e"},"number_format":{"separator":".","delimiter":","},"validators":{"user[first_name]":{"presence":[{"message":"can't be blank"}]},"user[last_name]":{"presence":[{"message":"can't be blank"}]},"user[phone]":{"presence":[{"message":"can't be blank"}]},"user[email]":{"uniqueness":[{"message":"has already been taken","case_sensitive":true,"allow_blank":true}],"format":[{"message":"is invalid","with":{"source":"^[^@\\s]+@[^@\\s]+$","options":"g"},"allow_blank":true}]},"user[password]":{"length":[{"messages":{"minimum":"is too short (minimum is 6 characters)","maximum":"is too long (maximum is 128 characters)"},"allow_blank":true,"minimum":6,"maximum":128}]}}}

**Comment by tagliala** [comment]
Hi,

thanks for reporting this.

Debugging CSV issues is hard and time consuming, please also past your `application.js`, `.erb` (`slim`/`haml`) template and the `html` generated output

**Comment by tagliala** [comment]
No feedback, closing here
