### ISSUE TITLE
Issues with presence:true validation in autocomplete input

### ISSUE THREAD

**Issue by JarLowrey** [DavyJonesLocker/client_side_validations#716]
I have an input with autocomplete setup where `presence: true`. If I select an option from the autocomplete, the error does not go away after focus has changed. I have to manually type something and then change focus. 

I have stepped thru the jQuery and the `presence` function inside the `validators` object is not triggered when I select something from the autocomplete pop-up menu.

**Comment by tagliala** [comment]
Hi,

which autocomplete library are you using? Did you test others?

**Comment by JarLowrey** [comment]
[jQuery autocomplete](https://jqueryui.com/autocomplete/). I have not tested any others, which would you recommend?

**Comment by tagliala** [comment]
Please check this wiki: https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins#jquery-plugins

you will probably need something like that

PS: please edit the wiki if you are able to find a solution

**Comment by JarLowrey** [comment]
Updated! Thanks for your help! https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins#jqueryui-autocomplete
