### ISSUE TITLE
validate: true property on for_form results on a weird html

### ISSUE THREAD

**Issue by NirvashType0** [DavyJonesLocker/client_side_validations#718]
### Steps to reproduce*
Just adding validate: true to a form_for
### Expected behavior*
The html output results on add data-validate="true"

### Actual behavior*
The html output results does not add data-validate="true" instead add data-client-side-validations="bunch of weird code"

### System configuration*
**Rails version**:5.3.1

**Ruby version**:2.3.4

**Client Side Validations version**: 9.3.4

### Code snippet from your model of the validations*
`class Invmtoproducto < ActiveRecord::Base
    self.table_name = 'invmtoproducto'
    self.primary_key = :codproducto
    validates :descripcion, presence: true
end`
### The whole form code from your template*
` <%= form_for @invmtoproducto, validate: true do |form| %>
        <div class="row rfrm">
             <fieldset>
             <legend>DATOS BASICOS:</legend>
                <div class="form-group col-md-5">
                    <%= form.label :Descripcion %>
                    <%= form.text_field :descripcion, id: :invmtoproducto_descripcion, class:'form-control' %>
                 </div>
             </fieldset>
         </div>
              <div class="actions">
                <%= form.submit "Guardar", class: "btn btn-success" %>
              </div>
  <% end %>`
### The resulting HTML*
`data-client-side-validations="{"html_settings":{"type":"ActionView::Helpers::FormBuilder","input_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003cspan id=\"input_tag\" /\u003e\u003clabel for=\"\" class=\"message\"\u003e\u003c/label\u003e\u003c/div\u003e","label_tag":"\u003cdiv class=\"field_with_errors\"\u003e\u003clabel id=\"label_tag\" /\u003e\u003c/div\u003e"},"number_format":{"separator":".","delimiter":","},"validators":{"invmtoproducto[descripcion]":{"presence":[{"message":"can't be blank"}]}}}"`

### Repository demostrating the issue

---

**\*** Failure to include this requirement will result in the issue being closed.

**Comment by tagliala** [comment]
Hi,

that is by design :)

That code represents the constraints against which the object will be validated.

Ref: #666

Please consider using [judge](https://github.com/joecorcoran/judge) if you need a different approach (separate javascript file for validations, which needs to be compiled and then referenced in the assets pipeline)

**Comment by NirvashType0** [comment]
Nope, I want to use the model validation with the gem :/ is there something I´m doing wrong?

**Comment by NirvashType0** [comment]
I solved the missing attribute tag with the next fix on the form_for tag:
'<%= form_for @invmtoproducto, data: {validate: true} do |form| %>
<% end %>' but still not working, the javascript for this is not working:

'$('.modal').on('shown.bs.modal', function() {
  $('form[data-validate]').enableClientSideValidations();
});'

**Comment by tagliala** [comment]
> document.addEventListener("turbolinks:load", function() { $('.modal').on('shown.bs.modal', function() { $('form[data-validate]').enableClientSideValidations(); }); });

why?

this code is related to hidden/dynamic forms added in bootstrap modals.

Please open a new issue explaining your problem

**Comment by NirvashType0** [comment]
OK, thank you!
