### ISSUE TITLE
Inline validations on ajax modals not showing

### ISSUE THREAD

**Issue by NirvashType0** [DavyJonesLocker/client_side_validations#720]
### Steps to reproduce*
1- Navigate to localhost:3000/invmtolineas
2-Click on 'Nueva Linea' button
3-Leave the form input blank and no validation is shown inline

### Expected behavior*
The inline validation should show after leaving the blank field

### Actual behavior*
No message showed, but at least seems like the validation is running cause the form cant be submited unless the field is not blank

### System configuration*
**Rails version**: 5.1.4

**Ruby version**: 2.3.3p222

**Client Side Validations version**: 9.3.4

### Code snippet from your model of the validations*
     class Invmtolinea < ApplicationRecord
	validates :nombre, presence: true
     end

### The whole form code from your template*

**Index:**

        <p id="notice"><%= notice %></p>
     <h1>Invmtolineas</h1>
    <%= link_to 'Nueva Linea', new_invmtolinea_path, :class => 'btn btn-success', remote: true, :title =>'Nuevo Linea', :data => { :toogle => 'tooltip', :placement => 'left'} %>
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
         <th>Codlinea</th>
         <th>Nombre</th>
         <th>Nis</th>
         <th>Feacceso</th>
         <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
        <% @invmtolineas.each do |invmtolinea| %>
          <tr>
            <td><%= invmtolinea.codlinea %></td>
            <td><%= invmtolinea.nombre %></td>
            <td><%= invmtolinea.nis %></td>
            <td><%= invmtolinea.feacceso %></td>
            <td><%= link_to 'Show', invmtolinea %></td>
            <td><%= link_to 'Edit', edit_invmtolinea_path(invmtolinea) %></td>
            <td><%= link_to 'Destroy', invmtolinea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
       <% end %>
     </tbody>
     </table>
     <br>
      <div id="modalW"></div>

**Modal partial**

       <div class="modal fade" id="myModal">
           <div class="modal-dialog">
             <div class="modal-content">
                <div class="modal-header">
                   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                   <h4 class="modal-title">Nueva Linea</h4>
                </div>
                <div class="modal-body">
      	             <%= render 'form', invmtolinea: @invmtolinea %>
                </div>
             </div>
          </div>
       </div>

**Partial rendered form in modal window**

       <%= simple_form_for(@invmtolinea, validate: true, remote: true) do |f| %>
          <% if @invmtolinea.errors.any? %>
              <div id="error_explanation">
                  <h2><%= pluralize(@invmtolinea.errors.count, "error") %> prohibited this invmtolinea from being saved:</h2>
                  <ul>
                       <% @invmtolinea.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                  </ul>
             </div>
          <% end %>
           <div class="form-group">
               <%= f.input :nombre, class: 'form-control' %>
           </div>
           <div class="actions">
              <%= f.button :submit %>
           </div>
        <% end %>

**Javascript to enableClientSideValidations on show.bs.modal (new.js.erb)**

         $('#modalW').html("<%= j (render 'new') %>");
         $('#myModal').on('shown.bs.modal', function () {
               $('form[data-validate]').enableClientSideValidations();
         }).modal('show');

### The resulting HTML* (modal resulting html)

      <div id="modalW"><div class="modal fade in" id="myModal" style="display: block;">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title">Nueva Linea</h4>
              </div>
              <div class="modal-body">
              	<form novalidate="novalidate" class="simple_form new_invmtolinea" id="new_invmtolinea" data-client-side-validations="{html_settings:{type:SimpleForm::FormBuilder,error_class:help-block,error_tag:span,wrapper_error_class:has-error,wrapper_tag:div,wrapper_class:form-group,wrapper:vertical_form},number_format:{separator:.,delimiter:,},validators:{invmtolinea[nombre]:{presence:[{message:can't be blank}]}}}" action="/invmtolineas" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓">
                         <div class="form-group">
                                 <div class="form-group string required invmtolinea_nombre"><label class="control-label string required" for="invmtolinea_nombre"><abbr title="required">*</abbr> Nombre</label><input class="form-control string required" type="text" name="invmtolinea[nombre]" id="invmtolinea_nombre"></div>
                         </div>
                         <div class="actions">
                                <input type="submit" name="commit" value="Create Invmtolinea" class="btn btn-default" data-disable-with="Create Invmtolinea">
                         </div>
        </form>
              </div>
            </div>
          </div>
        </div></div>

### Repository demostrating the issue

https://github.com/NirvashType0/modalcsv.git

---

**\*** Failure to include this requirement will result in the issue being closed.

**Comment by tagliala** [comment]
Hi.

Debugging CSV issues is extremely time consuming.

Could you please fix the code by properly using [github flavored markdown](https://guides.github.com/features/mastering-markdown/)

Also, using CSV with modals requires extra javascript, I also need that javascript.

In this case, I need that you should setup a repository demonstrating the issue to get an answer

**Comment by tagliala** [comment]
Of course, you should take a look at these wikies: 

- https://github.com/DavyJonesLocker/client_side_validations/wiki/Validating-dynamically-added-forms
- https://github.com/DavyJonesLocker/client_side_validations/wiki/Bootstrap-Modal-Validations

(in general: you need to configure a callback after the successfull ajax call to load client side validations. Also, you need a supported form builder in the generated modal. If the modal uses a different form builder, you need custom javascript code to properly add error messages)

**Comment by NirvashType0** [comment]
Im actually trying to style the post code!

**Comment by NirvashType0** [comment]
I already checked this link
https://github.com/DavyJonesLocker/client_side_validations/wiki/Bootstrap-Modal-Validations

Is the same javascript I´m using

**Comment by NirvashType0** [comment]
Repository uploaded!

**Comment by tagliala** [comment]
@NirvashType0 , thanks

As I said, debugging CSV issue is time consuming.

Please note that the repository should contain a reduced test case (as per [Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)):

> If you want to ensure that your issue gets fixed fast you should attempt to reproduce the issue in an **isolated example application** that you can share.

*emphasis mine*

Please just include the code (javascript and models) needed to reproduce the issue, and a step-by-step guide to reproduce it.

**Comment by NirvashType0** [comment]
I honestly cant find a way to share it with the db, so, ill share with you the project hosted on c9, if you want I can share with you access to the project to check the code!

**Comment by tagliala** [comment]
> I honestly cant find a way to share it with the db, 

Are persisted data needed?

If the answer is no, you should not share the db.

If the answer is yes, add just the minimum amount of data to replicate the issue to `db/seeds.rb`

Or use sqlite3 as database and commit `development.db` in the repository.

**Comment by NirvashType0** [comment]
I will upload the project with sqlite now! There is no need to include data since all I am doing is validate to add new data, I will update the steps to reproduce the r

**Comment by NirvashType0** [comment]
Done! Project uploaded with sqlite! Hope you can help me :D

**Comment by NirvashType0** [comment]
I added this javascript to my invmtolineas.js and actually I check with the browser console and  it seems to be catching the shown event everytime I open the modal but still no validation message being showed, maybe a problem related to the inputs or the form, I here the js:

       $(document).on('shown.bs.modal', "#myModal", function() {
	     $('form[data-validate]').enableClientSideValidations();
       });

**Comment by NirvashType0** [comment]
I guess I have just bad luck T.T maybe the jquery plugin for validations will be my final approach! Still hoping this can be solved :'D

**Comment by tagliala** [comment]
Hi @NirvashType0 

the problem was extremely simple: the wiki was not updated to the latest CSV, which is using `data-client-side-validations` instead of `data-validate`

I've updated the wiki with an idempotent event, so it should be compatible with turbolinks and jquery.

Here it is:

```coffee
$(document).on 'shown.bs.modal', '.modal', ->
  $('form[data-client-side-validations]').enableClientSideValidations()
```

Please translate to javascript if you need .js instead

Hope it helps

**Comment by NirvashType0** [comment]
Wow! I dint even though about this! Thanks man! :D you´re awesome!
