### ISSUE TITLE
Validation for uniqueness not working

### ISSUE THREAD

**Issue by yunshang** [DavyJonesLocker/client_side_validations#725]
### model code
```ruby
validates :name, uniqueness: true
```
### html code
```silm
= simple_form_for [:admin, @team], validate: true, html: { class: type } do |f|
  div(hint-css)
     label name
        = f.text_field :name, class: "form-control",placeholder: 'name'
```

### results screenshot
![aa](https://user-images.githubusercontent.com/5956306/32160950-d83ada86-bd21-11e7-9fc0-e7c08c0fce1d.png)
![image](https://user-images.githubusercontent.com/5956306/32161011-136f48ee-bd22-11e7-82de-6c7d4c10ed09.png)

Only the uniqueness validators not working, has been unable to find the problem.Sorry, English is very poor.

### System configuration*
**Rails version**:  5.1.4

**Ruby version**: 2.4.0

**Client Side Validations version**: 10.0.1

**Comment by tagliala** [comment]
Hi, uniqueness validator support was removed in version 7.0.

Ref: #512 #597 #612 #636 #659 #226 https://github.com/DavyJonesLocker/client_side_validations/issues/692#issuecomment-275408571
