### ISSUE TITLE
scripts not generated for multiple record creation via single form

### ISSUE THREAD

**Issue by dvodvo** [DavyJonesLocker/client_side_validations#732]
### Steps to reproduce*
Disabled old version of gem from the gem file.  New application requirements were needed for client side validations, and thus gem reinstalled.  also ran `rails g client_side_validations:install` just to be sure. `//= require rails.validations` is invoked after `//= require turbolinks`in the application.js pipeline configurator.  The 7-line block ` ActionView::Base.field_error_proc`  is uncommented.  *note* not sure what to do with the "encapsulated within" message that precedes this block... should it appear on the form?

The validations are called specifically on fields (conditional logic is short-circuited by the generation of the relevant forms for the context), i.e.

<%= g.text_field :document_number, validate: { presence: true } %>

restart of application after any modification to validation invocation.

### Expected behavior*
I expected the javascript regulating the validation to be generated before closing body tag.

### Actual behavior*
No script tag relating to validations is present.  And thus one can readily tab through the validatable fields and not be intercepted by the validation invoked.

### System configuration*
**Rails version**: 4.2.10

**Ruby version**: 2.3.4

**Client Side Validations version**:  4.2.12

### Code snippet from your model of the validations*
  validates :nome, presence: true
  validates :cognome, presence: true
  validates :email, presence: true
  validates :tareservation_id, presence: true
  validates :user_id, presence: true
  validates :nazione_id, presence: true, if: -> {!self.tareservation.event.eventcondition.nil?}
  validates :date_of_birth, presence: true, if: -> {!self.tareservation.event.eventcondition.nil?}
  validates :document_number, presence: true, if: -> {!self.tareservation.event.eventcondition.nil?}

### The whole form code from your template*
     form_tag pguests_path do 
       hidden_field_tag 'tareservation_id', @tareservation.id 
       @pguests.each do |pguest| 
         fields_for 'pguests[]', pguest, validate: true do |g| 
           class='row'
             class='small-6 medium-3 large-3 columns alert'
               t('nome') <br /
               g.text_field :nome, validate: { presence: true } 
### The resulting HTML (edited for brevity)*
    form action="/pguests?locale=en" accept-charset="UTF-8" method="post"input name="utf8" type="hidden" value="✓"
      input type="hidden" name="tareservation_id" id="tareservation_id" value="114"
          First name
          input type="text" name="pguests[][nome]" id="pguests__nome"

          Last Name
          input type="text" name="pguests[][cognome]" id="pguests__cognome"
          input value="75" type="hidden" name="pguests[][user_id]" id="pguests__user_id"

          e-mail
          input type="text" name="pguests[][email]" id="pguests__email"

          Date of Birth
          input start_year="1931" end_year="2018" format="date_latin2" type="date" name="pguests[][date_of_birth]" id="pguests__date_of_birth"

### Browser's development console output*
_Please confirm that your browser's development console does not contain errors._
console returns... [crickets]

### Additional JavaScript Libraries*
_If your issue depends on other JavaScript libraries, please list them here. E.g: *Bootstrap Modal v3.3.7, jQuery UI Datepicker 1.12.4*._

### Repository demostrating the issue

---

**\*** Failure to include this requirement will result in the issue being closed.

**Comment by tagliala** [comment]
Ciao!

thanks for reporting this.

Sorry, but I don't have resources to maintain a Rails 4.x compatible version of CSV.

If you are able to replicate this issue on CSV 11.0 / Rails 5.x I will definitely take a look.

Anyway, please note that:
* Your template uses `form_tag`, but CSV only works with `form_for`, as per [README](https://github.com/DavyJonesLocker/client_side_validations#usage)
* You should provide the whole HTML, including tags, without omissions
* Conditional validations are not evaluated, as per [README](https://github.com/DavyJonesLocker/client_side_validations#conditional-validators)

Closing here

**Comment by maxence33** [comment]
Hi @tagliala I am not as good as @dvodvo to report a problem insightfully but I experience the same problem with 2 forms on the same page ( Ruby 2.5, Rails 5.2)

This is regarding a Devise model where on my page I have two forms for the same model

`<%= form_for(resource, as: resource_name, url: registration_path(resource_name), validate: true) do |f| %>`

It works on the first form but not the second one.

**Comment by tagliala** [comment]
@maxence33 

Debugging CSV is time consuming, because it involves *almost* the whole application stack.

Please open a new issue and provide all the information required and I will take a look.

**Comment by maxence33** [comment]
Great thank you. I do this
