### ISSUE TITLE
'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by reckerswartz** [DavyJonesLocker/client_side_validations#733]
https://github.com/DavyJonesLocker/client_side_validations/blob/b393a8b419873f57c44c50624cee330268a013a6/coffeescript/rails.validations.coffee#L335
https://github.com/DavyJonesLocker/client_side_validations/blob/b393a8b419873f57c44c50624cee330268a013a6/coffeescript/rails.validations.coffee#L352

### Above line of codes produces error 
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive.

helpful links:-
* https://github.com/jamesallardice/jslint-error-explanations/blob/master/message-articles/function-constructor.md
* http://jslint.fantasy.codes/the-function-constructor-is-eval
## Environment
* Version used: 11.1
* Browser Name and version: Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro  (64-bit)

**Comment by tagliala** [comment]
Hi,

thanks for reporting this

A PR would be hugely appreciated

**Comment by reckerswartz** [comment]
Will provide PR soon.

**Comment by tagliala** [comment]
@reckerswartz thanks

I gave a fast look, it doesn't look easy

By the way, there are three calls to `Function` that should be addressed. The tokenizer seems the most complex. Fortunately, tokenizer option has been deprecated and we could bump the major version number and drop that feature

**Comment by reckerswartz** [comment]
@tagliala thanks for giving look to it.
tokenizer will be droped in PR.

**Comment by tagliala** [comment]
you're welcome, thank you!

Please make sure `rake test:js` passes

**Comment by reckerswartz** [comment]
rake test:js
Opening test app at http://localhost:4567 ...
== Sinatra (v2.0.0) has taken the stage on 8080 for development with backup from Thin
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:8080, CTRL+C to stop
ERROR: no web browser detected

error on cloud9.

**Comment by tagliala** [comment]
@reckerswartz javascript unit tests require a real browser installed on the machine. The browser should be configured to open links from the command line

I need help on this: #591

**Comment by reckerswartz** [comment]
Hey,
can you tell me how can I regenerate javascript after modifying CoffeeScript?

**Comment by tagliala** [comment]
`rake regenerate_javascript`

if you run the test, the javascript will be automatically regenerated

**Comment by tagliala** [comment]
@reckerswartz I've implemented this in 191a265
