### ISSUE TITLE
Validation should allow empty field value if use  allow_nil: true

### ISSUE THREAD

**Issue by soulfly** [DavyJonesLocker/client_side_validations#737]
I use the following validation in my Rails model:

```
  validates :website, length: {maximum: 200},
                                 format: {with: URI::regexp},
                              allow_nil: true
```
Unfortunately it does not allow me to save empty field value, I'm getting the following error when submit a form:
![image](https://user-images.githubusercontent.com/373137/38143583-db8c0cb0-3449-11e8-90dd-473988f73d44.png)

Looks like it comes from here
https://github.com/DavyJonesLocker/client_side_validations/blob/master/coffeescript/rails.validations.coffee#L287 

From my understanding we may need to add `return if options.allow_nil == true` as well there

And also replace the line
`hash[:allow_blank] = true if options[:allow_blank]`
with
`hash[:allow_blank] = true if options[:allow_nil] || options[:allow_blank]`

here https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model/length.rb#L30

So you already have it for 'numeric' validation here https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_model/numericality.rb#L44
so I propose to do the same for 'length' validation

Do you have any issues with the suggestion?

I use Rails 4.2 and 4.2.12 version of this gem but it looks like the issue is persist on master as well

**Comment by soulfly** [comment]
@tagliala do you have any feedback here? I'm also happy to prepare a PR on my side, just let me know is it worth trying.

**Comment by tagliala** [comment]
@soulfly thanks, will do that by myself on the master branch. I will also check for other "allow_blank"

btw I will not fix the old 4.2 branch

**Comment by soulfly** [comment]
Great thanks! 

> btw I will not fix the old 4.2 branch
that's fine, I will port your changes by myself to some custom branch

**Comment by tagliala** [comment]
@soulfly could you please give a try to the master branch?

**Comment by soulfly** [comment]
Thanks @tagliala ! I will give it a try
