### ISSUE TITLE
How can we add custom remote validator without the ClientSideValidations::Middleware::Base like in the wiki

### ISSUE THREAD

**Issue by dinatih** [DavyJonesLocker/client_side_validations#748]
wiki : https://github.com/DavyJonesLocker/client_side_validations/wiki/Custom-Validators#remote-validators
### System configuration

**Client Side Validations version**:
after this commit 35501c1b120a3d0d5b8a907e4edd6d7b826378e6

Is there another way to add custom remote validators, please ?

**Comment by dinatih** [comment]
Thanks you @factor4 I will try that.

**Comment by tagliala** [comment]
@factor4 thanks.

Still hadn't time to fix  the wiki

Please also be aware of information disclosure and DOS attacks: the above endpoints should be protected with something like [rack-attack](https://github.com/kickstarter/rack-attack)

**Comment by tagliala** [comment]
Wiki updated: https://github.com/DavyJonesLocker/client_side_validations/wiki/Custom-Validators#remote-validators
