### ISSUE TITLE
validate: false will still binds focusout event

### ISSUE THREAD

**Issue by symi** [DavyJonesLocker/client_side_validations#752]
If for example I have the following form where I want to validate all fields apart from one. I set `validate: true` on `form_for` and then `validate: false` for the field I wish to ignore.

```
<%= form_for(person, validate: true) do |form| %>
  ...
  <%= form.email_field :personal_email, { validate: false } %>
<% end %>
```

CSV will not run the server code to calculate the validation rules for this model field so `validators` JSON blob on the form has no entry for `person[personal_email]` which is correct. However the JS will run and the following line will pick up this input https://github.com/DavyJonesLocker/client_side_validations/blob/master/vendor/assets/javascripts/rails.validations.js#L203 and apply the focusout event handler (and https://github.com/DavyJonesLocker/client_side_validations/blob/master/vendor/assets/javascripts/rails.validations.js#L243 will actually add the data-attr of `data-validate: true` to the input).

The result is the field is 'pass'ed by CSV and so the pass and removeError code is ran for this field. My remove error logic adds a positive validation tick so the field gets the validation tick. 

When I set `validate: false` I expect CSV not to pick this field up for validation at all as I don't want the positive validation logic running. A way around this I thought would be to manually check for the presence of `data-validate=false` on the input inside my `remove` error handler, however CSV sets this data-attr to be true so it looks like it should be validated client side.

I can only think of using another data-attr which CSV won't interact with (which means I have to add both `validate: false` and something like `really-dont-validate: false` to the field) or I can manually look at the validators JSON blob and see if my field exists in there, however this requires me to replicate the complex logic in [`validatorsFor`](https://github.com/DavyJonesLocker/client_side_validations/blob/master/vendor/assets/javascripts/rails.validations.js#L53) to match on to the object keys from the field names, which isn't perfect either.

Another solution is I could manually remove the validation by unbind/calling `.disableClientSideValidations()` however again as data-validate is set to true I would have to expose another data-attr to see which inputs I need to run this on (I can't hard code the select to look for  `personal_email` as I want this to be generic and driven from the server flag).

Thanks for any help/thoughts on this.

### Steps to reproduce*

Add `{ validate: false }` to a field inside an enabled form.

### Expected behavior*

CSV should not attempt to bind handlers to this field and should not add `data-validate=true`.

### Actual behavior*

CSV runs on this field and fires the PASS events/remove error methods. and sets `data-validate=true`.

### System configuration*
**Rails version**:
5.1.6.1
**Ruby version**:
2.3.5
**Client Side Validations version**:
11.1.3
### Code snippet from your model of the validations*
-
### The whole form code from your template*
See above
### The resulting HTML*
`<input type="email" value="" id="person_personal_email" name="person[personal_email]" data-validate="true">`
### Browser's development console output*
-

### Additional JavaScript Libraries*
-

### Repository demostrating the issue
-

**Comment by tagliala** [comment]
Hi,

I've investigated this issue and I can confirm that there is something going on.

Anyway, `validate: false` (as well as the implicit `validate: true`) does not add information to the input element, so there is actually no chance to understand if a field is going to perform validation or if it doesn't.

`validate: false` removes the validation entry for its field in the `data-client-side-validation` attribute of the `<form>` object.

I would keep the things as they are, document this case, and leave the user the choice if the field must do something while getting his `pass` callback

If you don't want that a field performs a pass callback, then you can use a css class

```erb
<%= f.input :name, validate: false, input_html: { class: 'skip-is-valid-j' } %>
```

```coffee
ClientSideValidations.callbacks.element.pass = ($element, callback, eventData) ->
  return if $element.hasClass('skip-is-valid-j')

  $element.addClass('is-valid')
  callback()
```

or check if the field has validations associated

```coffee
ClientSideValidations.callbacks.element.pass = ($element, callback, eventData) ->
  return unless $element[0].form.ClientSideValidations.settings.validators[$element[0].name]?

  $element.addClass('is-valid')
  callback()
```

Hope it helps

Closing here

**Comment by symi** [comment]
For anyone that stubbles across this in the future. I ended up going down the additional class route. I use a custom form builder so might end up encapsulating the logic in there. Before CSV form helpers run check the options and if `validate: false` exists add my custom class to the html options. 

Would like to use the `$element[0].form.ClientSideValidations.settings.validators[$element[0].name]` solution in the `pass` callback but this won't work for things like `model[0][attribute]` as this isn't a direct mapping into the `validators` object.

Thanks for the help.
