### ISSUE TITLE
Error running rails g client_side_validations:install

### ISSUE THREAD

**Issue by chibuezeayogu** [DavyJonesLocker/client_side_validations#754]
I followed the steps in the README.md
 -  I added the gem then ran the command `rails g client_side_validations:install`
and this is the error I got.

```
Could not find generator 'client_side_validations:install'. Maybe you meant 'integration_test', 'rspec:install' or 'test_unit:system'
Run `rails generate --help` for more options.
```
Please, I am I missing?

**Comment by tagliala** [comment]
Hi,

did you run `bundle install` before?

**Comment by chibuezeayogu** [comment]
@tagliala yes I did

**Comment by tagliala** [comment]
@chibuezeayogu does it work after?

**Comment by chibuezeayogu** [comment]
@tagliala no it didn't work

**Comment by tagliala** [comment]
Please try the following

```sh
bundle info client_side_validations
```

Please confirm that you see something like

```
  * client_side_validations (13.0.0)
	Summary: Client Side Validations
	Homepage: https://github.com/DavyJonesLocker/client_side_validations
	Path: ~/.rvm/gems/ruby-2.6.1/gems/client_side_validations-13.0.0
```

If you don't see that, please check that your `Gemfile` contains 

```rb
gem 'client_side_validations'
```

And it is not inside a group (eg: it is not under `test`, or `production`)

Then, when the above point is met, please try

```sh
rails g client_side_validations:instal
```

or 

```sh
bundle exec rails g client_side_validations:instal
```

Let me know

**Comment by chibuezeayogu** [comment]
@tagliala 
![Screen Shot 2019-03-11 at 4 27 22 PM](https://user-images.githubusercontent.com/26305570/54135802-c7985b00-441a-11e9-88bb-a2f50750a8ed.png)

**Comment by tagliala** [comment]
Please try `spring stop` and retry

**Comment by chibuezeayogu** [comment]
@tagliala Yea It worked. thanks

**Comment by tagliala** [comment]
You're welcome!
