### ISSUE TITLE
How can i use this validations with bootstrap-select plugin?

### ISSUE THREAD

**Issue by es-daniel** [DavyJonesLocker/client_side_validations#758]
https://developer.snapappointments.com/bootstrap-select/

**Comment by tagliala** [comment]
Hi,

this could help: https://github.com/DavyJonesLocker/client_side_validations/wiki/Select2-Validation

**Comment by tagliala** [comment]
Maybe also:
- https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins#bootstrap-datepicker-rails
- https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins#bootstrap-datetimepicker-3

**Comment by tagliala** [comment]
If you still have questions, please provide more information and I will reopen

Meanwhile, closing here
