### ISSUE TITLE
conditional validation undefined

### ISSUE THREAD

**Issue by dvodvo** [DavyJonesLocker/client_side_validations#760]
The instructions on the `README` state

    validates :name, :email, presence: true, length: { maximum: 10 }, if: :can_validate?
is it me or do I not see some confusion by invoking both name and email (the maximum length is what makes me say 'wat?')

In any instance, I have a model where
```
  validates :email, presence: true, if: :can_validate?

  def can_validate
    true
  end
```
and the form

```
<%= form_for @taguest, url: create_concert_guest_taguests_path, validate: true, html: { method: :post} do |f| %>
[...]
<%= f.text_field :email, validate: true %>
```
this returns error `undefined method 'can_validate?' for #<Guest:0x000055a9408ffe28>
Did you mean?  can_validate`.  The error disappears when `, validate: true` is removed, thus confirming that the model method is being invoked.

Thus **something is off** (and maybe my confusion is blinding me)

**Comment by tagliala** [comment]
Hi,

> The instructions on the `README` state
> 
> ```
> validates :name, :email, presence: true, length: { maximum: 10 }, if: :can_validate?
> ```
>

That is fine. It is conditionally validating presence and length against both `name` and `email` fields.

Refs:
- https://guides.rubyonrails.org/active_record_validations.html#presence
- https://api.rubyonrails.org/v5.2.3/classes/ActiveModel/Validations/ClassMethods.html#method-i-validates

> is it me or do I not see some confusion by invoking both name and email (the maximum length is what makes me say 'wat?')
> 

Oh, yes. Definitely. I will fix that example

> In any instance, I have a model where
> 
> ```
>   validates :email, presence: true, if: :can_validate?
> 
>   def can_validate
>     true
>   end
> ```
> 
> and the form
> 
> ```
> <%= form_for @taguest, url: create_concert_guest_taguests_path, validate: true, html: { method: :post} do |f| %>
> [...]
> <%= f.text_field :email, validate: true %>
> ```
> 
> this returns error `undefined method 'can_validate?' for #<Guest:0x000055a9408ffe28> Did you mean? can_validate`. The error disappears when `, validate: true` is removed, thus confirming that the model method is being invoked.
> 
> Thus **something is off** (and maybe my confusion is blinding me)

The method name should be `can_validate?` with the trailing question mark

Hope it helps

**Comment by dvodvo** [comment]
> Hope it helps

It certainly did!
