### ISSUE TITLE
Multiple fields validations on rails5

### ISSUE THREAD

**Issue by no1-knows** [DavyJonesLocker/client_side_validations#765]
I'm a newbie using rails.
First of all thank you for your client_side_validations!
This is very useful.

The multiple-fields wiki page is good for rails5?

[https://github.com/DavyJonesLocker/client_side_validations/wiki/Shared-validations-for-multiple-fields
](https://github.com/DavyJonesLocker/client_side_validations/wiki/Shared-validations-for-multiple-fields
)

I tried and get error message like 'undefined method `-' for nil:NilClass' at below code.
```
def great_small_fields_diff
        great_field - small_field
 end
```
I can't judge this is because of rails version or not but I'm worried about published date which is 2012...

**Comment by tagliala** [comment]
Hi,

`'undefined method `-' for nil:NilClass'` means that you are trying to subtract `nil` to something else. I think your model does not define `great_field` or its corresponding field. Please take a look to [Rails Activee Record Basics](https://guides.rubyonrails.org/active_record_basics.html)

About the wiki: https://github.com/DavyJonesLocker/client_side_validations/wiki/Shared-validations-for-multiple-fields

Quoting from the wiki:

> For example you want the value of a field to be greater than another

Well, the example is outdated and I'm not a fan of the approach suggested by that wiki.

If you just need that kind of validation, the numericality validator offers that kind of validation out of the box: https://guides.rubyonrails.org/active_record_validations.html#numericality

```rb
validates :small_field, numericality: { greater_than: 0 }
validates :great_field, numericality: { greater_than: :small_field }
```

It works on the client side in a lot of cases (other cases will be anyhow covered on the server side). Ref: #687

If you really need (check what Rails offers first) special validations, I advise you to create a custom local validator (both server side and client side) as described in this wiki: https://github.com/DavyJonesLocker/client_side_validations/wiki/Custom-Validators and assign it to a specific field.

If the client side validation is too complex and requires custom validations are still not enough, consider using a standard jQuery callback when all validations pass and rails is ready to submit the form:

Hope it helps

Closing here, but feel free to comment

**Comment by no1-knows** [comment]
@tagliala  thank you for reply!

'undefined method `-' for nil:NilClass’ is solved!
But wiki way doesn’t work because error don’t show up at diplay:none object.

For me, this wiki is easy to understand and your offer, create a custom validator, is difficult for me. 

As far as I know,  phone, zip code, name or something like that use several fields in form and only 1 table column is used in most cases.
So I hope not to divide these table column.

Is there any easy approach to solve this problem at this awesome gem?

**Comment by tagliala** [comment]
> But wiki way doesn’t work because error don’t show up at diplay:none object.

You should avoid that `display:none` form field 😅 

What you need to validate?

**Comment by no1-knows** [comment]
Hello!
What I need to validate is zip code, name, phone number.
And select2 thing, which is just required therefore jQuery is better maybe?

Actually 2 or 3 table columns in DB for name is one of the solutions.

-3 columns in table-
| Justin | Drew | Bieber |

But I think the below is smarter.

-1 column in table-
| Justin Drew Bieber | 


My ideal situation is to validate these above things with no javascript, which is normal usage of this awesome gem.

As far as I know, rails is one of best way for startup project.
If this gem works these commonly used function, validation setting is very simple which makes app reliability.

If I have skill, I would like to revise this awesome gem for attr_accessor.

**Comment by tagliala** [comment]
You're welcome, glad you've solved
