### ISSUE TITLE
isValid is not a function

### ISSUE THREAD

**Issue by lkibbalam** [DavyJonesLocker/client_side_validations#770]
### Steps to reproduce*
call isValid on form
$input     = $('#myInputField');
$form      = $input.closest('form');
validators = $form[0].ClientSideValidations.settings.validators;
$form.isValid(validators);

### Expected behaviour*
$form.isValid(validators) schould validate each form's field

### Actual behaviour*
isValid is not a function

### System configuration*
Rails 6
ruby 2.6.4
client_side_validations (16.0.1)

### The whole form code from your template*
```
<%= form_for(@user, :url => wizard_path, :method => :put, validate: true, html: { id: 'userForm', class: 'new_user' }) do |form| %>
      <p class="form-description text">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero provident dicta itaque laborum veniam, vel impedit laudantium neque totam !
      </p>
      <div class="form-group">
        <%= form.label :first_name, 'First Name', class: 'form-label' %>
        <div class="form-control">
          <%= form.text_field :first_name, value: @user.first_name, class: 'input', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :last_name, 'Surname', class: 'form-label' %>
        <div class="form-control">
          <%= form.text_field :last_name, value: @user.last_name, class: 'input', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :email, 'Email adress', class: 'form-label' %>
        <div class="form-control">
          <%= form.email_field :email, value: @user.email, class: 'input', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :telephone, 'Telephone', class: 'form-label' %>
        <div class="form-control">
          <%= form.text_field :telephone, value: @user.telephone, class: 'input', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= form.label :company_name, 'Company name', class: 'form-label' %>
        <div class="form-control">
          <%= form.text_field :company_name, value: @user.company_name, class: 'input', required: true %>
        </div>
      </div>
      <div class="form-secondary-description">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis magnam perspiciatis quisquam vero eum nesciunt earum deleniti alias placeat vitae!
      </div>
      <div class="form-group">
        <div class="form-control form-control-checkbox">
          <%= form.check_box :terms_of_service, class:'checkbox', required: true  %>
          <%= form.label :terms_of_service, id: :user_terms_of_service, class: 'form-label' do %>
            <%= "Opt-in" %>
          <% end %>
        </div>
      </div>
      <%= recaptcha_tags(callback: 'enableSubmitBtn') unless @user.persisted? %>
      <%= form.submit('Let\'s go', class: "button button-primary button-mobile button-disabled", id: 'submitBtn') %>
    <% end %>
```

### Additional JavaScript Libraries*

"dependencies": {
    "@client-side-validations/client-side-validations": "^0.0.4",
    "@rails/actioncable": "^6.0.0-alpha",
    "@rails/activestorage": "^6.0.0-alpha",
    "@rails/ujs": "^6.0.0-alpha",
    "@rails/webpacker": "^4.0.7",
    "chart.js": "^2.8.0",
    "chartkick": "^3.1.1",
    "jquery": "^3.4.1",
    "turbolinks": "^5.2.0"
  }

application.js
require("@rails/ujs").start()
// require("turbolinks").start() affects client side validations
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("chartkick")
require("chart.js")
import '@client-side-validations/client-side-validations'

validators = $form[0].ClientSideValidations.settings.validators;  - returns expected answer

another issue is if in application.js
require('@client-side-validations/client-side-validations')

I catch the bug with $form[0].ClientSideValidations is null

It's weird for me. Looks like I do something wrong but I am walking around this issue for a week

Thank you

**Comment by tagliala** [comment]
Hi,

thanks for being part of the CSV community

Please try the following

1. In your use case, you have to use the `require` approach. Then, feel free to uncomment Turbolinks. Please take a look at the readme.

2. `$form[0].ClientSideValidations` is null
CSV is attaching to forms on document ready or `turbolinks:load`/`page:change`, so please check that you are doing that inside after CSV has been initialized

**Comment by lkibbalam** [comment]
> Hi,
> 
> thanks for being part of the CSV community
> 
> Please try the following
> 
> 1. In your use case, you have to use the `require` approach. Then, feel free to uncomment Turbolinks. Please take a look at the readme.
> 2. `$form[0].ClientSideValidations` is null
>    CSV is attaching to forms on document ready or `turbolinks:load`/`page:change`, so please check that you are doing that inside after CSV has been initialized

2.Yes. I tried it before.
I wrapped the code into $( document ).ready(function() {
but stille have the same result
result from my console
```
step1:123 Uncaught TypeError: $form.isValid is not a function
    at HTMLInputElement.<anonymous> (step1:123)
    at HTMLInputElement.dispatch (event.js:328)
    at HTMLInputElement.elemData.handle (event.js:148)
(anonymous) @ step1:123
dispatch @ event.js:328
elemData.handle @ event.js:148
```
```
$( document ).ready(function() {
    $form = $('#userForm');
    validators = $form[0].ClientSideValidations.settings.validators;
    $.each( $($('#userForm').get(0).elements).not(':hidden') ,function(){
      $(this).on('change', function() {
        if($form.isValid(validators)) {
          $form.find(':submit').removeClass('button-disabled');
        } else {
          $form.find(':submit').addClass('button-disabled');
        }
      })
    });
  })
```

1.Turbolinks affects my forms if I make step back. CVS just doesn't work without page reloading

**Comment by tagliala** [comment]
> 1.Turbolinks affects my forms if I make step back. CVS just doesn't work without page reloading

That should not happen. You mean when you use `back` ?

**Comment by lkibbalam** [comment]
> > 1.Turbolinks affects my forms if I make step back. CVS just doesn't work without page reloading
> 
> That should not happen. You mean when you use `back` ?

yes, by browser button for example

**Comment by tagliala** [comment]
Ok, will also try that

**Comment by tagliala** [comment]
Hi @lkibbalam ,

I had a chance to test this and I think I've got the issue.

Basically, you need to run some tests on a CSV-enabled form.

So we have to ensure two things:
1. The form exists on the page
2. Client Side Validations has been initialized

The problem above is that the initializer code is running on all pages, even if the form is not present. And if we wrap it inside document.ready, we will lose the "turbolinks:load" event.

Given that you need to use `require`, the proper way of running custom code is the following:

```js
const customCsvInitialization = () => {
  var $form = $('#new_foo')

  // 1. Ensure that the form is on the page
  if (!$form.length) {
    return
  }

  // Your custom code
  $form.isValid($form[0].ClientSideValidations.settings.validators)
}

// 2. Ensure that CSV has been initialized
if (window.Turbolinks != null && window.Turbolinks.supported) {
  $(document).on('turbolinks:load', customCsvInitialization)
} else {
  $(customCsvInitialization)
}
```

In order to improve this approach, I could add a callback when CSV has been initialized, but at the moment I have few time for this.

PR with proper unit tests are welcomed

**Comment by tagliala** [comment]
I'm going to close this issue, will open a feature request
