### ISSUE TITLE
Confirmation field is always validated

### ISSUE THREAD

**Issue by patricklindsay** [DavyJonesLocker/client_side_validations#774]
### Steps to reproduce*

This maybe a question more than an issue with CSV but I'm trying to make email confirmation sometimes required and sometimes optional depending on the circumstances.

Note when testing the validation 

### Expected behavior*
By default CSV should not validate email confirmation because it is conditional. If `validate: true` is passed then it should validate.

### Actual behavior*
Always validates `email_confirmation` regardless of what `validate_email_confirmation?` returns

Note: testing this out serverside validations work as expected

### System configuration*
**Rails version**: 5.2

**Ruby version**: 2.4.1

**Client Side Validations version**:
    client_side_validations (11.1.3)
    client_side_validations-simple_form (6.10.0)

### Code snippet from your model of the validations*
```
    validates :email, presence: true, confirmation: true
    validates :email_confirmation, presence: true, if: :validate_email_confirmation?
```

### The whole form code from your template*
```
        = simple_form_for @contact_message, validate: true  do |f|
          = f.input :email
          = f.input :email_confirmation
```

### Browser's development console output*
- [x] I confirm that my browser's development console output does not contain errors

### Additional JavaScript Libraries*
_If your issue depends on other JavaScript libraries, please list them here. E.g: *Bootstrap Modal v3.3.7, jQuery UI Datepicker 1.12.4*._
N/A
### Repository demostrating the issue
Debugging CSV issues is a time consuming task. If you want to speed up things, please
provide a link to a repository showing the issue.
- I can provide if required
---

**\*** Failure to include this requirement may result in the issue being closed.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the CSV Community and sorry for the late reply.

> The resulting HTML*

Could you please provide the resulting html? Since it contains all the information needed by CSV, it is easier to check what it is going on

**Comment by tagliala** [comment]
Closing here because of missing feedback
