### ISSUE TITLE
I use bootstrap_form_for and it was written using your example but it didn't work

### ISSUE THREAD

**Issue by RanX12** [DavyJonesLocker/client_side_validations#777]
### Expected behavior*
I use bootstrap_form_for and it was written using your example but it didn't work

### System configuration*
**Rails version 6.0:

**Ruby version 2.5:

**Client Side Validations version**:
@client-side-validations/client-side-validations@^0.1.1

### Code snippet from your model of the validations*
  validates :name, presence: true
  validates :company_name, presence: true
  validates :company_email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }, presence: true
  validates :phone, presence: true
  validates :team_size, presence: true
  validates :recruitment, presence: true
  validates :online_time, presence: true
  validates :other_question, presence: true

### The whole form code from your template*
= bootstrap_form_for @company_custom_infos, validate: true do |f|
  .card-body.form-body
    .company_custom_infos
      = f.text_field :name,  label:'name'
      = f.text_field :company_name, label:'company_name'
      = f.phone_field :phone, label:'phone'
      = f.text_field :company_email,  label:'company_email'
      = f.form_group :team_size, class:'team-size', label: { text: 'team_size' }
        = f.radio_button :team_size, '1~10', label:'1~10'
        = f.radio_button :team_size, '11~30', label:'11~30'
        = f.radio_button :team_size, '31~50', label:'31~50'
        = f.radio_button :team_size, '50+', label:'50+'
      = f.form_group :recruitment, class:'radio-form-group', label: { text: 'recruitment' }
        = f.radio_button :recruitment, '1~10', label:'1~10'
        = f.radio_button :recruitment, '11~30', label:'11~30'
        = f.radio_button :recruitment, '31~50', label:'31~50'
        = f.radio_button :recruitment, '50+', label:'50+'
      = f.form_group :online_time, class:'radio-form-group', label: { text: 'online_time' }
        = f.radio_button :online_time, '1~2', label:'1~2'
        = f.radio_button :online_time, '3~4', label:'3~4'
        = f.radio_button :online_time, '5~6', label:'5~6'
        = f.radio_button :online_time, '6+', label:'6+'
      = f.text_area :other_question, as: :text, label: 'other_question'
      .action
        = f.submit 'submit', class: 'btn btn-primary'

### Browser's development console output*
No

### Additional JavaScript Libraries*
bootstrap_form 4.2.0

### Repository demostrating the issue
Debugging CSV issues is a time consuming task. If you want to speed up things, please
provide a link to a repository showing the issue.

---

**\*** Failure to include this requirement may result in the issue being closed.

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the CSV Community.

> bootstrap_form_for

Sorry, this is not supported

You can consider `simple_form`: https://github.com/DavyJonesLocker/client_side_validations-simple_form

Hope it helps

Closing here
