### ISSUE TITLE
Not able to get yarn package

### ISSUE THREAD

**Issue by kushthedude** [DavyJonesLocker/client_side_validations#799]
### Steps to reproduce*
- `yarn add @client-side-validations/client-side-validations` gives timeout error.

### Expected behavior*
Package should get installed properly.

### Actual behavior*
```sh
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

### System configuration*
**Rails version**:
6.0.0
**Ruby version**:
2.5.0
**Client Side Validations version**:
Not getting installed

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the CSV Community.

Can't confirm. CSV is using the public yarn repository. It could be a temporary error with your network or with yarn itself

In fact, I'm getting an error 500 while trying to check yarn's status at https://status.yarnpkg.com/

**Comment by kushthedude** [comment]
Hi @tagliala , thanks for heads-up! I am still unable to access the package.

**Comment by tagliala** [comment]
please try with npm instead of yarn

**Comment by kushthedude** [comment]
> please try with npm instead of yarn

Worked! Thanks
