### ISSUE TITLE
Failure against Ruby 3.0 / Rails 6.0

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#821]
https://travis-ci.org/github/DavyJonesLocker/client_side_validations/jobs/753686007

This is fixed on Rails `6-0-stable` branch, just waiting for a new release

Ref: rails/rails#39697

**Comment by sushantmittal** [comment]
I am facing this issue as well.

**Comment by tagliala** [comment]
Hi @sushantmittal, this is an issue in rails and the fix has not been released.

Please use the latest `6-0-stable`. Other gems are affected, take a look at this commit from devise: https://github.com/heartcombo/devise/commit/2e68cdea9b1ff3e08835ddb6be42d9ec774a0d6d

**Comment by sushantmittal** [comment]
Hi @tagliala, Thanks for the response.
I forked the repository and did the required change in `gemfiles/rails_6.0.gemfile`: `gem "rails", '~> 6.0.0', github: 'rails/rails', branch: '6-0-stable'` as you suggested. After that, I used this forked repo gem in my app but I am still getting this issue:

`wrong argument type Hash (expected String)`. It is same as you are getting here: https://travis-ci.org/github/DavyJonesLocker/client_side_validations/jobs/753686007#L411

**Comment by tagliala** [comment]
Hi @sushantmittal 

> After that, I used this forked repo gem in my app but I am still getting this issue:

If you are having this issue in your app, please edit your app's Gemfile

Replace `gem "rails"` with: `gem "rails", '~> 6.0.0', github: 'rails/rails', branch: '6-0-stable'`

No need to fork this repo, the issue is in rails

**Comment by sushantmittal** [comment]
ok thanks @tagliala.

**Comment by tagliala** [comment]
Fixed in Rails 6.0.4
