### ISSUE TITLE
validation firing but without messages

### ISSUE THREAD

**Issue by dvodvo** [DavyJonesLocker/client_side_validations#822]
Installation on Rails 6.0 with ruby 2.6.2
  "dependencies": {
    "@client-side-validations/client-side-validations": "^0.1.5",
 devise, ~> 4.7.3
 devise-i18n, ~> 1.9, >= 1.9.2

The devise password field (also defined as 6..40 in the devise initializer)
``` 
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40}
```
note the above block is necessary as the devise initializers appear to be ingored without it
```
<%= form_for(resource, as: resource_name, validate: true, url: registration_path(resource_name)) do |f| %>
[...] 
<div class='grid-x grid-padding-x'>
    <div class='cell small-12 '>
      <%= f.label :password %>
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>
  </div>
```

is, upon tabbing after after less than the minimum characters,
changing the background color by changing the class as expected
 `<div class="field_with_errors">` of both the label and the password_field but the error message is not shown, 
![Screen Shot 2021-01-27 at 14 03 26](https://user-images.githubusercontent.com/716130/105995256-05eba180-60a9-11eb-878c-943238edf14c.png)
notwithstanding the form has the proper content.  The image also alludes to the fact that the text is not arriving, as the character height is apparently absent.  Follows are form elements and snippet of CSS
```

<form class="new_user" id="new_user" novalidate="novalidate" data-client-side-validations="{ [...]
&quot;user[password]&quot;:{&quot;length&quot;:[{&quot;messages&quot;:{&quot;minimum&quot;:&quot;is too short (minimum is 6 characters)
&quot;,&quot;maximum&quot;:&quot;is too long (maximum is 40 characters)&quot;}
[...]
<div class="field_with_errors"><input autocomplete="new-password" type="password" name="user[password]" id="user_password" data-validate="true"></div>

.message {
  border-bottom-right-radius: 5px 5px;
  border-top-right-radius: 5px 5px;
  padding: 2px 5px;
}
div.field_with_errors div.ui-effects-wrapper {
  display: inline-block !important;
}

```
- [X ] I confirm that my browser's development console output does not contain errors

What could be at play here?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the CSV Community.

Debugging CSV issue is a time consuming task. Could you please fill out the [bug report template](https://github.com/DavyJonesLocker/client_side_validations/issues/new?assignees=&labels=&template=bug_report.md&title=) in all sections and even better provide a reproducible (and reduced) test case?

**Comment by tagliala** [comment]
> Sorry,. For the form, I enclose the elements that have javascipt components that may influence it (avoiding a long collection_select scroll):

Apologies for the late reply

Yes, of course this can influence CSV

Please take a look here: https://github.com/DavyJonesLocker/client_side_validations/wiki/Select2-Validation
