### ISSUE TITLE
[Bug] Nested form breaks for `f.fields`

### ISSUE THREAD

**Issue by AquisTech** [DavyJonesLocker/client_side_validations#827]
### Steps to reproduce*
Setup all the other required associations and accepts_nested_attributes also build nested_associations in controller (this part works without CSV)
Following part breaks when CSV is added.
```HAML
= f.form_with(model: @user) do |f|
  = f.text_field :name
  = f.fields :addresses do |ad|
    = ad.text_field :address_line_1
```

### Expected behavior*
Should render form & nested form correctly

### Actual behavior*
Breaks with following error
```
ActionView::Template::Error (wrong number of arguments (given 2, expected 0..1)):
    1: = f.fields :addresses do |ad|
    2:   = ad.text_field :address_line_1
```

### System configuration*
**Rails version**:
6.1.0

**Ruby version**:
2.7.1

**Client Side Validations version**:
18.0.0

### Code snippet from your model of the validations*
Not needed

### The whole form code from your template*
```HAML
= f.form_with(model: @user) do |f|
  = f.text_field :name
  = f.fields :addresses do |ad|
    = ad.text_field :address_line_1
```

### The resulting HTML*
Breaks to generate HTML

### Browser's development console output*
- [x] I confirm that my browser's development console output does not contain errors

### Additional JavaScript Libraries*
None. It's a Rails side issue

### Repository demostrating the issue
I have forked the CSV repo to debug issue locally. I will provide PR with the bugfix :adhesive_bandage: 

---

**\*** Failure to include this requirement may result in the issue being closed.

**Comment by AquisTech** [comment]
Raised PR #828

**Comment by tagliala** [comment]
@AquisTech before the release, could you pleas try the `main` branch and provide some feedback?
