### ISSUE TITLE
Add Turbo compatibility

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#835]
https://github.com/hotwired/turbo-rails

**Comment by enderwiggens** [comment]
Any update on this - we are in the progress of migrating our project to Turbo and noticed that this gem is no longer working.

**Comment by tagliala** [comment]
Hi

> Would be happy to contribute - has anyone diagnosed the issue yet?

Thanks for your willing to help, a PR would be very welcomed

The problem is how to identify Turbo, since it is not exposed to the window object by default and it is advised not to be exposed

This problem can be solved once for all if we move to idempotent events. I have an outdated branch with some changes here: https://github.com/DavyJonesLocker/client_side_validations/tree/idempotent-events

**Comment by tagliala** [comment]
> The problem is how to identify Turbo, since it is not exposed to the window object by default and it is advised not to be exposed

From [Turbo Rails readme](https://github.com/hotwired/turbo-rails#installation):

> Turbo is automatically started (and assigned to window.Turbo) upon importation.

https://github.com/hotwired/turbo-rails/commit/82f5e002863fea0a5605a3a48b4c6501c46da7f8

Ok, so now we can detect it and act accordingly 🥳
